[package]
name = "sampling"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
rand_distr = {workspace = true}
rand_chacha = { workspace = true }
rand_core = { workspace = true }