[package]
name = "rlwe"
version = "0.1.0"
edition = "2024"

[dependencies]
rug = {workspace = true}
criterion = {workspace = true}
base2k = {path="../base2k"}
sampling = {path="../sampling"}
rand_distr = {workspace = true}
itertools = {workspace = true}
