use crate::tfhe::bdd_arithmetic::{BitCircuit, BitCircuitInfo, Circuit, GetBitCircuitInfo, Node};
pub(crate) enum AnyBitCircuit {
    B0(BitCircuit<4>),
    B1(BitCircuit<8>),
    B2(BitCircuit<18>),
    B3(BitCircuit<24>),
    B4(BitCircuit<30>),
    B5(BitCircuit<36>),
    B6(BitCircuit<42>),
    B7(BitCircuit<48>),
    B8(BitCircuit<54>),
    B9(BitCircuit<60>),
    B10(BitCircuit<66>),
    B11(BitCircuit<72>),
    B12(BitCircuit<78>),
    B13(BitCircuit<84>),
    B14(BitCircuit<90>),
    B15(BitCircuit<96>),
    B16(BitCircuit<102>),
    B17(BitCircuit<108>),
    B18(BitCircuit<114>),
    B19(BitCircuit<120>),
    B20(BitCircuit<126>),
    B21(BitCircuit<132>),
    B22(BitCircuit<138>),
    B23(BitCircuit<144>),
    B24(BitCircuit<150>),
    B25(BitCircuit<156>),
    B26(BitCircuit<162>),
    B27(BitCircuit<168>),
    B28(BitCircuit<174>),
    B29(BitCircuit<180>),
    B30(BitCircuit<186>),
    B31(BitCircuit<192>),
}
impl BitCircuitInfo for AnyBitCircuit {
    fn info(&self) -> (&[Node], usize) {
        match self {
            AnyBitCircuit::B0(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B1(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B2(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B3(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B4(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B5(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B6(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B7(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B8(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B9(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B10(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B11(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B12(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B13(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B14(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B15(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B16(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B17(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B18(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B19(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B20(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B21(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B22(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B23(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B24(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B25(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B26(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B27(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B28(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B29(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B30(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B31(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
        }
    }
}

impl GetBitCircuitInfo<u32> for Circuit<AnyBitCircuit, 32usize> {
    fn input_size(&self) -> usize {
        2 * u32::BITS as usize
    }
    fn output_size(&self) -> usize {
        u32::BITS as usize
    }
    fn get_circuit(&self, bit: usize) -> (&[Node], usize) {
        self.0[bit].info()
    }
}

pub(crate) static OUTPUT_CIRCUITS: Circuit<AnyBitCircuit, 32usize> = Circuit([
    AnyBitCircuit::B0(BitCircuit::new(
        [
            Node::Cmux(32, 1, 0),
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B1(BitCircuit::new(
        [
            Node::Cmux(33, 0, 1),
            Node::Cmux(33, 1, 0),
            Node::Cmux(1, 1, 0),
            Node::Cmux(1, 0, 1),
            Node::Cmux(32, 0, 1),
            Node::Copy,
            Node::Cmux(0, 0, 1),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B2(BitCircuit::new(
        [
            Node::Cmux(34, 0, 1),
            Node::None,
            Node::Cmux(34, 1, 0),
            Node::None,
            Node::Cmux(2, 0, 2),
            Node::Cmux(2, 2, 0),
            Node::Cmux(33, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(1, 2, 0),
            Node::Cmux(1, 0, 1),
            Node::Cmux(32, 1, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(0, 0, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B3(BitCircuit::new(
        [
            Node::Cmux(35, 1, 0),
            Node::None,
            Node::Cmux(35, 0, 1),
            Node::Cmux(3, 2, 0),
            Node::Cmux(3, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 1, 0),
            Node::None,
            Node::Cmux(2, 2, 0),
            Node::Cmux(2, 1, 2),
            Node::Cmux(33, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(1, 2, 0),
            Node::None,
            Node::Cmux(1, 0, 1),
            Node::Cmux(32, 0, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(0, 0, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B4(BitCircuit::new(
        [
            Node::Cmux(36, 1, 0),
            Node::Cmux(36, 0, 1),
            Node::None,
            Node::Cmux(4, 0, 1),
            Node::None,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::None,
            Node::Cmux(3, 1, 2),
            Node::Copy,
            Node::Cmux(34, 0, 2),
            Node::Copy,
            Node::Cmux(2, 1, 2),
            Node::Cmux(2, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 1, 0),
            Node::None,
            Node::Cmux(1, 2, 0),
            Node::Cmux(1, 1, 2),
            Node::Cmux(32, 2, 1),
            Node::Copy,
            Node::None,
            Node::Cmux(0, 0, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B5(BitCircuit::new(
        [
            Node::Cmux(37, 0, 1),
            Node::None,
            Node::Cmux(37, 1, 0),
            Node::Cmux(5, 0, 2),
            Node::None,
            Node::Cmux(5, 2, 0),
            Node::Copy,
            Node::Cmux(36, 2, 0),
            Node::Copy,
            Node::Cmux(4, 2, 1),
            Node::None,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(3, 1, 2),
            Node::Cmux(3, 0, 1),
            Node::Cmux(34, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(2, 2, 0),
            Node::Cmux(2, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 0, 1),
            Node::Cmux(1, 2, 1),
            Node::None,
            Node::Cmux(1, 0, 2),
            Node::Copy,
            Node::Cmux(32, 2, 0),
            Node::None,
            Node::Cmux(0, 1, 0),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B6(BitCircuit::new(
        [
            Node::Cmux(38, 1, 0),
            Node::Cmux(38, 0, 1),
            Node::None,
            Node::None,
            Node::Cmux(6, 0, 1),
            Node::Cmux(6, 1, 0),
            Node::Cmux(37, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(5, 0, 2),
            Node::Cmux(5, 1, 0),
            Node::Cmux(36, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(4, 0, 1),
            Node::None,
            Node::Cmux(4, 2, 0),
            Node::Copy,
            Node::Cmux(35, 2, 0),
            Node::Copy,
            Node::Cmux(3, 2, 1),
            Node::None,
            Node::Cmux(3, 1, 0),
            Node::Copy,
            Node::Cmux(34, 0, 2),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::Cmux(2, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 0, 1),
            Node::Cmux(1, 0, 2),
            Node::Cmux(1, 2, 1),
            Node::None,
            Node::None,
            Node::Copy,
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B7(BitCircuit::new(
        [
            Node::Cmux(39, 0, 1),
            Node::None,
            Node::Cmux(39, 1, 0),
            Node::Cmux(7, 2, 0),
            Node::None,
            Node::Cmux(7, 0, 2),
            Node::Copy,
            Node::Cmux(38, 0, 2),
            Node::Copy,
            Node::Cmux(6, 1, 2),
            Node::None,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(37, 2, 0),
            Node::Copy,
            Node::Cmux(5, 2, 1),
            Node::None,
            Node::Cmux(5, 1, 0),
            Node::Copy,
            Node::Cmux(36, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(4, 0, 1),
            Node::Cmux(4, 1, 2),
            Node::Cmux(35, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::Cmux(3, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::Cmux(2, 2, 1),
            Node::Cmux(2, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 1, 0),
            Node::Cmux(1, 1, 2),
            Node::Cmux(1, 2, 0),
            Node::None,
            Node::None,
            Node::Copy,
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B8(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(40, 0, 1),
            Node::Cmux(40, 1, 0),
            Node::Cmux(8, 2, 1),
            Node::Cmux(8, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 0, 1),
            Node::Cmux(7, 2, 1),
            Node::None,
            Node::Cmux(7, 0, 2),
            Node::Copy,
            Node::Cmux(38, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(6, 1, 0),
            Node::Cmux(6, 2, 1),
            Node::Cmux(37, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::None,
            Node::Cmux(5, 2, 0),
            Node::Copy,
            Node::Cmux(36, 2, 0),
            Node::Copy,
            Node::Cmux(4, 2, 1),
            Node::Cmux(4, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(35, 0, 1),
            Node::Cmux(3, 0, 2),
            Node::Cmux(3, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::None,
            Node::Cmux(2, 2, 1),
            Node::Cmux(2, 0, 2),
            Node::Cmux(33, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(1, 2, 0),
            Node::None,
            Node::Cmux(1, 0, 1),
            Node::None,
            Node::Cmux(32, 0, 2),
            Node::Copy,
            Node::Cmux(0, 1, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B9(BitCircuit::new(
        [
            Node::Cmux(41, 0, 1),
            Node::Cmux(41, 1, 0),
            Node::None,
            Node::Cmux(9, 0, 1),
            Node::Cmux(9, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 1, 0),
            Node::Cmux(8, 2, 0),
            Node::Cmux(8, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 1, 0),
            Node::Cmux(7, 2, 0),
            Node::Cmux(7, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 1, 0),
            Node::Cmux(6, 1, 2),
            Node::None,
            Node::Cmux(6, 2, 0),
            Node::Copy,
            Node::Cmux(37, 0, 2),
            Node::Copy,
            Node::Cmux(5, 1, 2),
            Node::None,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(36, 2, 0),
            Node::Copy,
            Node::Cmux(4, 2, 1),
            Node::None,
            Node::Cmux(4, 1, 0),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::Cmux(3, 1, 2),
            Node::None,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(34, 2, 0),
            Node::Copy,
            Node::Cmux(2, 1, 0),
            Node::None,
            Node::Cmux(2, 2, 1),
            Node::Copy,
            Node::Cmux(33, 2, 0),
            Node::Copy,
            Node::Cmux(1, 2, 1),
            Node::Cmux(1, 1, 0),
            Node::None,
            Node::None,
            Node::Copy,
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B10(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(42, 0, 1),
            Node::Cmux(42, 1, 0),
            Node::None,
            Node::Cmux(10, 1, 2),
            Node::Cmux(10, 2, 1),
            Node::Cmux(41, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(9, 2, 0),
            Node::Cmux(9, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 0, 1),
            Node::Cmux(8, 2, 1),
            Node::Cmux(8, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 1, 0),
            Node::Cmux(7, 1, 2),
            Node::Cmux(7, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 0, 1),
            Node::None,
            Node::Cmux(6, 2, 1),
            Node::Cmux(6, 0, 2),
            Node::Cmux(37, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::Cmux(5, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 1, 0),
            Node::Cmux(4, 1, 2),
            Node::None,
            Node::Cmux(4, 2, 0),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Cmux(3, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::Cmux(2, 0, 2),
            Node::None,
            Node::Cmux(2, 2, 1),
            Node::Copy,
            Node::Cmux(33, 0, 2),
            Node::Copy,
            Node::Cmux(1, 0, 1),
            Node::Cmux(1, 1, 2),
            Node::None,
            Node::None,
            Node::Copy,
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B11(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(43, 1, 0),
            Node::Cmux(43, 0, 1),
            Node::Cmux(11, 1, 2),
            Node::None,
            Node::Cmux(11, 2, 1),
            Node::Copy,
            Node::Cmux(42, 0, 2),
            Node::Copy,
            Node::Cmux(10, 1, 2),
            Node::Cmux(10, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 1, 0),
            Node::Cmux(9, 2, 0),
            Node::None,
            Node::Cmux(9, 1, 2),
            Node::Copy,
            Node::Cmux(40, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(8, 1, 0),
            Node::Cmux(8, 2, 1),
            Node::Cmux(39, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(7, 2, 0),
            Node::None,
            Node::Cmux(7, 0, 1),
            Node::Copy,
            Node::Cmux(38, 0, 2),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Cmux(6, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(37, 0, 1),
            Node::None,
            Node::Cmux(5, 2, 1),
            Node::Cmux(5, 0, 2),
            Node::Cmux(36, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(4, 2, 0),
            Node::Cmux(4, 0, 1),
            Node::Cmux(35, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(3, 1, 0),
            Node::Cmux(3, 0, 2),
            Node::Cmux(34, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(2, 0, 2),
            Node::Cmux(2, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 1, 0),
            Node::Cmux(1, 1, 2),
            Node::Cmux(1, 2, 0),
            Node::None,
            Node::Cmux(32, 0, 1),
            Node::Copy,
            Node::None,
            Node::Cmux(0, 0, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B12(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(44, 0, 1),
            Node::Cmux(44, 1, 0),
            Node::Cmux(12, 1, 2),
            Node::Cmux(12, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 1, 0),
            Node::None,
            Node::Cmux(11, 1, 2),
            Node::Cmux(11, 2, 0),
            Node::Cmux(42, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(10, 0, 2),
            Node::Cmux(10, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 1, 0),
            Node::None,
            Node::Cmux(9, 1, 2),
            Node::Cmux(9, 2, 0),
            Node::Cmux(40, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Cmux(8, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 0, 1),
            Node::None,
            Node::Cmux(7, 2, 1),
            Node::Cmux(7, 0, 2),
            Node::Cmux(38, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(6, 2, 0),
            Node::None,
            Node::Cmux(6, 0, 1),
            Node::Copy,
            Node::Cmux(37, 0, 2),
            Node::Copy,
            Node::Cmux(5, 1, 2),
            Node::None,
            Node::Cmux(5, 0, 1),
            Node::Copy,
            Node::Cmux(36, 2, 0),
            Node::Copy,
            Node::Cmux(4, 1, 0),
            Node::Cmux(4, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(35, 1, 0),
            Node::Cmux(3, 2, 0),
            Node::None,
            Node::Cmux(3, 1, 2),
            Node::Copy,
            Node::Cmux(34, 2, 0),
            Node::Copy,
            Node::Cmux(2, 1, 0),
            Node::None,
            Node::Cmux(2, 2, 1),
            Node::Copy,
            Node::Cmux(33, 2, 0),
            Node::Copy,
            Node::Cmux(1, 1, 0),
            Node::Cmux(1, 2, 1),
            Node::None,
            Node::Copy,
            Node::Cmux(32, 1, 0),
            Node::None,
            Node::Cmux(0, 1, 0),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B13(BitCircuit::new(
        [
            Node::Cmux(45, 0, 1),
            Node::None,
            Node::Cmux(45, 1, 0),
            Node::None,
            Node::Cmux(13, 2, 0),
            Node::Cmux(13, 0, 2),
            Node::Cmux(44, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(12, 1, 0),
            Node::Cmux(12, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 0, 1),
            Node::Cmux(11, 0, 2),
            Node::Cmux(11, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(42, 0, 1),
            Node::None,
            Node::Cmux(10, 2, 1),
            Node::Cmux(10, 0, 2),
            Node::Cmux(41, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(9, 2, 0),
            Node::None,
            Node::Cmux(9, 0, 1),
            Node::Copy,
            Node::Cmux(40, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(8, 1, 2),
            Node::Cmux(8, 0, 1),
            Node::Cmux(39, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::None,
            Node::Cmux(7, 2, 0),
            Node::Copy,
            Node::Cmux(38, 2, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Cmux(6, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(37, 1, 0),
            Node::None,
            Node::Cmux(5, 1, 2),
            Node::Cmux(5, 2, 0),
            Node::Cmux(36, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(4, 1, 0),
            Node::Cmux(4, 0, 2),
            Node::Cmux(35, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(3, 0, 2),
            Node::None,
            Node::Cmux(3, 1, 0),
            Node::Copy,
            Node::Cmux(34, 2, 0),
            Node::Copy,
            Node::Cmux(2, 2, 1),
            Node::Cmux(2, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 0, 1),
            Node::Cmux(1, 2, 1),
            Node::Cmux(1, 0, 2),
            Node::None,
            Node::Copy,
            Node::None,
            Node::Cmux(32, 1, 0),
            Node::Cmux(0, 2, 0),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B14(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(46, 0, 1),
            Node::Cmux(46, 1, 0),
            Node::Cmux(14, 1, 2),
            Node::None,
            Node::Cmux(14, 2, 1),
            Node::Copy,
            Node::Cmux(45, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(13, 2, 1),
            Node::Cmux(13, 1, 0),
            Node::Cmux(44, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(12, 1, 0),
            Node::Cmux(12, 0, 2),
            Node::Cmux(43, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(11, 0, 2),
            Node::None,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(42, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(10, 1, 0),
            Node::Cmux(10, 2, 1),
            Node::Cmux(41, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(9, 2, 0),
            Node::Cmux(9, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 0, 1),
            Node::None,
            Node::Cmux(8, 2, 1),
            Node::Cmux(8, 0, 2),
            Node::Cmux(39, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(7, 2, 0),
            Node::Cmux(7, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 0, 1),
            Node::None,
            Node::Cmux(6, 0, 2),
            Node::Cmux(6, 2, 1),
            Node::Cmux(37, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Cmux(5, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 0, 1),
            Node::Cmux(4, 2, 1),
            Node::Cmux(4, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(35, 1, 0),
            Node::Cmux(3, 2, 0),
            Node::None,
            Node::Cmux(3, 1, 2),
            Node::Copy,
            Node::Cmux(34, 2, 0),
            Node::Copy,
            Node::Cmux(2, 1, 0),
            Node::None,
            Node::Cmux(2, 2, 1),
            Node::Copy,
            Node::Cmux(33, 2, 0),
            Node::Copy,
            Node::Cmux(1, 2, 1),
            Node::None,
            Node::Cmux(1, 1, 0),
            Node::None,
            Node::Cmux(32, 0, 2),
            Node::Copy,
            Node::Cmux(0, 1, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B15(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(47, 0, 1),
            Node::Cmux(47, 1, 0),
            Node::None,
            Node::Cmux(15, 2, 1),
            Node::Cmux(15, 1, 2),
            Node::Cmux(46, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(14, 0, 2),
            Node::Cmux(14, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(45, 1, 0),
            Node::Cmux(13, 2, 0),
            Node::None,
            Node::Cmux(13, 1, 2),
            Node::Copy,
            Node::Cmux(44, 2, 0),
            Node::Copy,
            Node::Cmux(12, 2, 1),
            Node::Cmux(12, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 0, 1),
            Node::Cmux(11, 0, 2),
            Node::Cmux(11, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(42, 0, 1),
            Node::Cmux(10, 2, 1),
            Node::None,
            Node::Cmux(10, 0, 2),
            Node::Copy,
            Node::Cmux(41, 2, 0),
            Node::Copy,
            Node::Cmux(9, 2, 1),
            Node::Cmux(9, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 0, 1),
            Node::Cmux(8, 0, 2),
            Node::Cmux(8, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 0, 1),
            Node::Cmux(7, 2, 1),
            Node::Cmux(7, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 1, 0),
            Node::Cmux(6, 2, 0),
            Node::None,
            Node::Cmux(6, 1, 2),
            Node::Copy,
            Node::Cmux(37, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(5, 2, 1),
            Node::Cmux(5, 1, 0),
            Node::Cmux(36, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(4, 1, 0),
            Node::Cmux(4, 0, 2),
            Node::Cmux(35, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(3, 0, 2),
            Node::Cmux(3, 1, 0),
            Node::Cmux(34, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(2, 0, 1),
            Node::Cmux(2, 2, 0),
            Node::Cmux(33, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(1, 2, 0),
            Node::Cmux(1, 0, 1),
            Node::Cmux(32, 1, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(0, 0, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B16(BitCircuit::new(
        [
            Node::Cmux(48, 1, 0),
            Node::None,
            Node::Cmux(48, 0, 1),
            Node::Cmux(16, 0, 2),
            Node::None,
            Node::Cmux(16, 2, 0),
            Node::Copy,
            Node::Cmux(47, 0, 2),
            Node::Copy,
            Node::Cmux(15, 1, 2),
            Node::Cmux(15, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 1, 0),
            Node::None,
            Node::Cmux(14, 1, 2),
            Node::Cmux(14, 2, 0),
            Node::Cmux(45, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Cmux(13, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(44, 0, 1),
            Node::Cmux(12, 2, 1),
            Node::Cmux(12, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 1, 0),
            Node::Cmux(11, 2, 0),
            Node::None,
            Node::Cmux(11, 1, 2),
            Node::Copy,
            Node::Cmux(42, 2, 0),
            Node::Copy,
            Node::Cmux(10, 1, 0),
            Node::Cmux(10, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 1, 0),
            Node::Cmux(9, 2, 0),
            Node::Cmux(9, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 1, 0),
            Node::None,
            Node::Cmux(8, 1, 2),
            Node::Cmux(8, 2, 0),
            Node::Cmux(39, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(7, 1, 0),
            Node::Cmux(7, 0, 2),
            Node::Cmux(38, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(6, 0, 2),
            Node::Cmux(6, 1, 0),
            Node::Cmux(37, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 2, 0),
            Node::Cmux(5, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 0, 1),
            Node::Cmux(4, 2, 1),
            Node::None,
            Node::Cmux(4, 0, 2),
            Node::Copy,
            Node::Cmux(35, 2, 0),
            Node::Copy,
            Node::Cmux(3, 2, 1),
            Node::Cmux(3, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::Cmux(2, 2, 1),
            Node::None,
            Node::Cmux(2, 0, 2),
            Node::Copy,
            Node::Cmux(33, 2, 0),
            Node::Copy,
            Node::Cmux(1, 2, 1),
            Node::Cmux(1, 1, 0),
            Node::None,
            Node::None,
            Node::Copy,
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B17(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(49, 1, 0),
            Node::Cmux(49, 0, 1),
            Node::Cmux(17, 1, 2),
            Node::Cmux(17, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(48, 0, 1),
            Node::Cmux(16, 2, 1),
            Node::Cmux(16, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 1, 0),
            Node::Cmux(15, 2, 0),
            Node::Cmux(15, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 1, 0),
            Node::Cmux(14, 1, 2),
            Node::None,
            Node::Cmux(14, 2, 0),
            Node::Copy,
            Node::Cmux(45, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(13, 0, 1),
            Node::Cmux(13, 1, 2),
            Node::Cmux(44, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(12, 0, 2),
            Node::None,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(43, 2, 0),
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::None,
            Node::Cmux(11, 2, 1),
            Node::Copy,
            Node::Cmux(42, 2, 0),
            Node::Copy,
            Node::Cmux(10, 2, 1),
            Node::Cmux(10, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 0, 1),
            Node::Cmux(9, 2, 1),
            Node::None,
            Node::Cmux(9, 0, 2),
            Node::Copy,
            Node::Cmux(40, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(8, 2, 1),
            Node::Cmux(8, 1, 0),
            Node::Cmux(39, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(7, 0, 2),
            Node::None,
            Node::Cmux(7, 1, 0),
            Node::Copy,
            Node::Cmux(38, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(6, 1, 0),
            Node::Cmux(6, 2, 1),
            Node::Cmux(37, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 2, 0),
            Node::Cmux(5, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 0, 1),
            Node::Cmux(4, 2, 1),
            Node::Cmux(4, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(35, 1, 0),
            Node::Cmux(3, 1, 2),
            Node::Cmux(3, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::None,
            Node::Cmux(2, 0, 2),
            Node::Cmux(2, 2, 1),
            Node::Cmux(33, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(1, 0, 2),
            Node::None,
            Node::Cmux(1, 1, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(32, 2, 0),
            Node::Cmux(0, 2, 0),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B18(BitCircuit::new(
        [
            Node::Cmux(50, 0, 1),
            Node::Cmux(50, 1, 0),
            Node::None,
            Node::Cmux(18, 0, 1),
            Node::Cmux(18, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(49, 1, 0),
            Node::Cmux(17, 1, 2),
            Node::None,
            Node::Cmux(17, 2, 0),
            Node::Copy,
            Node::Cmux(48, 0, 2),
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Cmux(16, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 0, 1),
            Node::Cmux(15, 2, 1),
            Node::Cmux(15, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 1, 0),
            Node::None,
            Node::Cmux(14, 2, 0),
            Node::Cmux(14, 1, 2),
            Node::Cmux(45, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::Cmux(13, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(44, 1, 0),
            Node::None,
            Node::Cmux(12, 1, 2),
            Node::Cmux(12, 2, 0),
            Node::Cmux(43, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(11, 0, 2),
            Node::None,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(42, 2, 0),
            Node::Copy,
            Node::Cmux(10, 2, 1),
            Node::Cmux(10, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 0, 1),
            Node::Cmux(9, 0, 2),
            Node::Cmux(9, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 0, 1),
            Node::Cmux(8, 2, 1),
            Node::Cmux(8, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 1, 0),
            Node::Cmux(7, 1, 2),
            Node::None,
            Node::Cmux(7, 2, 0),
            Node::Copy,
            Node::Cmux(38, 0, 2),
            Node::Copy,
            Node::Cmux(6, 1, 2),
            Node::Cmux(6, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(37, 1, 0),
            Node::None,
            Node::Cmux(5, 2, 0),
            Node::Cmux(5, 1, 2),
            Node::Cmux(36, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(4, 2, 0),
            Node::None,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::None,
            Node::Cmux(3, 1, 2),
            Node::Copy,
            Node::Cmux(34, 0, 2),
            Node::Copy,
            Node::Cmux(2, 1, 2),
            Node::None,
            Node::Cmux(2, 0, 1),
            Node::Copy,
            Node::Cmux(33, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(1, 2, 1),
            Node::Cmux(1, 1, 0),
            Node::None,
            Node::Cmux(32, 1, 2),
            Node::Copy,
            Node::Cmux(0, 1, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B19(BitCircuit::new(
        [
            Node::Cmux(51, 0, 1),
            Node::None,
            Node::Cmux(51, 1, 0),
            Node::Cmux(19, 2, 0),
            Node::Cmux(19, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(50, 0, 1),
            Node::None,
            Node::Cmux(18, 2, 1),
            Node::Cmux(18, 0, 2),
            Node::Cmux(49, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(17, 2, 0),
            Node::Cmux(17, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(48, 0, 1),
            Node::Cmux(16, 0, 2),
            Node::Cmux(16, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 0, 1),
            Node::Cmux(15, 2, 1),
            Node::None,
            Node::Cmux(15, 0, 2),
            Node::Copy,
            Node::Cmux(46, 2, 0),
            Node::Copy,
            Node::Cmux(14, 1, 0),
            Node::None,
            Node::Cmux(14, 2, 1),
            Node::Copy,
            Node::Cmux(45, 2, 0),
            Node::Copy,
            Node::Cmux(13, 2, 1),
            Node::Cmux(13, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(44, 0, 1),
            Node::None,
            Node::Cmux(12, 0, 2),
            Node::Cmux(12, 2, 1),
            Node::Cmux(43, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(11, 0, 2),
            Node::Cmux(11, 1, 0),
            Node::Cmux(42, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(10, 2, 0),
            Node::None,
            Node::Cmux(10, 0, 1),
            Node::Copy,
            Node::Cmux(41, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(9, 0, 1),
            Node::Cmux(9, 1, 2),
            Node::Cmux(40, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(8, 1, 0),
            Node::Cmux(8, 0, 2),
            Node::Cmux(39, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(7, 0, 2),
            Node::Cmux(7, 1, 0),
            Node::Cmux(38, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(6, 2, 0),
            Node::Cmux(6, 0, 1),
            Node::Cmux(37, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 1, 0),
            Node::Cmux(5, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 0, 1),
            Node::Cmux(4, 2, 1),
            Node::None,
            Node::Cmux(4, 0, 2),
            Node::Copy,
            Node::Cmux(35, 2, 0),
            Node::Copy,
            Node::Cmux(3, 2, 1),
            Node::Cmux(3, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::None,
            Node::Cmux(2, 2, 1),
            Node::Cmux(2, 0, 2),
            Node::Cmux(33, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(1, 2, 0),
            Node::Cmux(1, 0, 1),
            Node::Cmux(32, 1, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(0, 0, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B20(BitCircuit::new(
        [
            Node::Cmux(52, 0, 1),
            Node::Cmux(52, 1, 0),
            Node::None,
            Node::None,
            Node::Cmux(20, 0, 1),
            Node::Cmux(20, 1, 0),
            Node::Cmux(51, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(19, 2, 0),
            Node::Cmux(19, 0, 1),
            Node::Cmux(50, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Cmux(18, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(49, 0, 1),
            Node::Cmux(17, 2, 1),
            Node::Cmux(17, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(48, 1, 0),
            Node::Cmux(16, 1, 2),
            Node::Cmux(16, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 0, 1),
            Node::Cmux(15, 0, 2),
            Node::Cmux(15, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 0, 1),
            Node::Cmux(14, 2, 1),
            Node::None,
            Node::Cmux(14, 0, 2),
            Node::Copy,
            Node::Cmux(45, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(13, 2, 1),
            Node::Cmux(13, 1, 0),
            Node::Cmux(44, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(12, 0, 2),
            Node::Cmux(12, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 1, 0),
            Node::None,
            Node::Cmux(11, 2, 0),
            Node::Cmux(11, 1, 2),
            Node::Cmux(42, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(10, 2, 0),
            Node::Cmux(10, 0, 1),
            Node::Cmux(41, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::Cmux(9, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 0, 1),
            Node::Cmux(8, 2, 1),
            Node::Cmux(8, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 1, 0),
            Node::None,
            Node::Cmux(7, 1, 2),
            Node::Cmux(7, 2, 0),
            Node::Cmux(38, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::None,
            Node::Cmux(6, 0, 2),
            Node::Copy,
            Node::Cmux(37, 0, 2),
            Node::Copy,
            Node::Cmux(5, 1, 2),
            Node::Cmux(5, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 1, 0),
            Node::Cmux(4, 1, 2),
            Node::None,
            Node::Cmux(4, 2, 0),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Cmux(3, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::Cmux(2, 2, 1),
            Node::Cmux(2, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 1, 0),
            Node::Cmux(1, 2, 0),
            Node::Cmux(1, 1, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(32, 1, 0),
            Node::None,
            Node::Cmux(0, 1, 0),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B21(BitCircuit::new(
        [
            Node::Cmux(53, 0, 1),
            Node::Cmux(53, 1, 0),
            Node::None,
            Node::None,
            Node::Cmux(21, 0, 1),
            Node::Cmux(21, 1, 0),
            Node::Cmux(52, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(20, 0, 1),
            Node::None,
            Node::Cmux(20, 2, 0),
            Node::Copy,
            Node::Cmux(51, 2, 0),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::Cmux(19, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(50, 1, 0),
            Node::Cmux(18, 2, 0),
            Node::Cmux(18, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(49, 1, 0),
            Node::None,
            Node::Cmux(17, 2, 0),
            Node::Cmux(17, 1, 2),
            Node::Cmux(48, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(16, 2, 0),
            Node::Cmux(16, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 0, 1),
            Node::Cmux(15, 2, 1),
            Node::Cmux(15, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 1, 0),
            Node::Cmux(14, 2, 0),
            Node::None,
            Node::Cmux(14, 1, 2),
            Node::Copy,
            Node::Cmux(45, 2, 0),
            Node::Copy,
            Node::Cmux(13, 1, 0),
            Node::Cmux(13, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(44, 1, 0),
            Node::Cmux(12, 1, 2),
            Node::Cmux(12, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 0, 1),
            Node::Cmux(11, 0, 2),
            Node::None,
            Node::Cmux(11, 2, 1),
            Node::Copy,
            Node::Cmux(42, 0, 2),
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::Cmux(10, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 0, 1),
            Node::None,
            Node::Cmux(9, 0, 2),
            Node::Cmux(9, 2, 1),
            Node::Cmux(40, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(8, 0, 2),
            Node::None,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(39, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(7, 2, 1),
            Node::Cmux(7, 1, 0),
            Node::Cmux(38, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(6, 1, 0),
            Node::Cmux(6, 0, 2),
            Node::Cmux(37, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 0, 2),
            Node::Cmux(5, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 1, 0),
            Node::Cmux(4, 1, 2),
            Node::Cmux(4, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(35, 0, 1),
            Node::Cmux(3, 2, 1),
            Node::Cmux(3, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 1, 0),
            Node::None,
            Node::Cmux(2, 1, 2),
            Node::Cmux(2, 2, 0),
            Node::Cmux(33, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(1, 0, 2),
            Node::Cmux(1, 1, 0),
            Node::None,
            Node::Copy,
            Node::Cmux(32, 2, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B22(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(54, 0, 1),
            Node::Cmux(54, 1, 0),
            Node::Cmux(22, 1, 2),
            Node::Cmux(22, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(53, 1, 0),
            Node::Cmux(21, 2, 0),
            Node::Cmux(21, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(52, 1, 0),
            Node::Cmux(20, 1, 2),
            Node::Cmux(20, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(51, 0, 1),
            Node::Cmux(19, 0, 2),
            Node::None,
            Node::Cmux(19, 2, 1),
            Node::Copy,
            Node::Cmux(50, 0, 2),
            Node::Copy,
            Node::Cmux(18, 0, 1),
            Node::None,
            Node::Cmux(18, 1, 2),
            Node::Copy,
            Node::Cmux(49, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(17, 1, 2),
            Node::Cmux(17, 0, 1),
            Node::Cmux(48, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Cmux(16, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 1, 0),
            Node::None,
            Node::Cmux(15, 2, 0),
            Node::Cmux(15, 1, 2),
            Node::Cmux(46, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(14, 2, 0),
            Node::None,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(45, 0, 2),
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::None,
            Node::Cmux(13, 1, 2),
            Node::Copy,
            Node::Cmux(44, 0, 2),
            Node::Copy,
            Node::Cmux(12, 1, 2),
            Node::Cmux(12, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 1, 0),
            Node::Cmux(11, 1, 2),
            Node::Cmux(11, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(42, 0, 1),
            Node::Cmux(10, 0, 2),
            Node::None,
            Node::Cmux(10, 2, 1),
            Node::Copy,
            Node::Cmux(41, 0, 2),
            Node::Copy,
            Node::Cmux(9, 1, 2),
            Node::Cmux(9, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 1, 0),
            Node::None,
            Node::Cmux(8, 2, 0),
            Node::Cmux(8, 1, 2),
            Node::Cmux(39, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Cmux(7, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 1, 0),
            Node::Cmux(6, 2, 0),
            Node::None,
            Node::Cmux(6, 1, 2),
            Node::Copy,
            Node::Cmux(37, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(5, 2, 1),
            Node::Cmux(5, 1, 0),
            Node::Cmux(36, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(4, 0, 2),
            Node::Cmux(4, 1, 0),
            Node::Cmux(35, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(3, 0, 1),
            Node::Cmux(3, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 1, 0),
            Node::None,
            Node::Cmux(2, 2, 0),
            Node::Cmux(2, 1, 2),
            Node::Cmux(33, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(1, 2, 0),
            Node::Cmux(1, 0, 1),
            Node::Cmux(32, 1, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(0, 0, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B23(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(55, 1, 0),
            Node::Cmux(55, 0, 1),
            Node::Cmux(23, 1, 2),
            Node::None,
            Node::Cmux(23, 2, 1),
            Node::Copy,
            Node::Cmux(54, 0, 2),
            Node::Copy,
            Node::Cmux(22, 1, 2),
            Node::None,
            Node::Cmux(22, 0, 1),
            Node::Copy,
            Node::Cmux(53, 2, 0),
            Node::Copy,
            Node::Cmux(21, 1, 0),
            Node::Cmux(21, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(52, 1, 0),
            Node::Cmux(20, 1, 2),
            Node::Cmux(20, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(51, 0, 1),
            Node::Cmux(19, 0, 2),
            Node::None,
            Node::Cmux(19, 2, 1),
            Node::Copy,
            Node::Cmux(50, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(18, 1, 2),
            Node::Cmux(18, 0, 1),
            Node::Cmux(49, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(17, 0, 1),
            Node::Cmux(17, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(48, 1, 0),
            Node::Cmux(16, 1, 2),
            Node::Cmux(16, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 0, 1),
            Node::Cmux(15, 2, 1),
            Node::Cmux(15, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 1, 0),
            Node::Cmux(14, 2, 0),
            Node::None,
            Node::Cmux(14, 1, 2),
            Node::Copy,
            Node::Cmux(45, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(13, 1, 0),
            Node::Cmux(13, 2, 1),
            Node::Cmux(44, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(12, 2, 0),
            Node::Cmux(12, 0, 1),
            Node::Cmux(43, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Cmux(11, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(42, 0, 1),
            Node::Cmux(10, 2, 1),
            Node::None,
            Node::Cmux(10, 0, 2),
            Node::Copy,
            Node::Cmux(41, 2, 0),
            Node::Copy,
            Node::Cmux(9, 1, 0),
            Node::None,
            Node::Cmux(9, 2, 1),
            Node::Copy,
            Node::Cmux(40, 2, 0),
            Node::Copy,
            Node::Cmux(8, 2, 1),
            Node::Cmux(8, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 0, 1),
            Node::Cmux(7, 2, 1),
            Node::None,
            Node::Cmux(7, 0, 2),
            Node::Copy,
            Node::Cmux(38, 2, 0),
            Node::Copy,
            Node::Cmux(6, 1, 0),
            Node::Cmux(6, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(37, 1, 0),
            Node::Cmux(5, 2, 0),
            Node::Cmux(5, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 1, 0),
            Node::Cmux(4, 1, 2),
            Node::None,
            Node::Cmux(4, 2, 0),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::Cmux(3, 1, 2),
            Node::None,
            Node::Cmux(3, 0, 1),
            Node::Copy,
            Node::Cmux(34, 2, 0),
            Node::Copy,
            Node::Cmux(2, 1, 0),
            Node::None,
            Node::Cmux(2, 2, 1),
            Node::Copy,
            Node::Cmux(33, 2, 0),
            Node::Copy,
            Node::Cmux(1, 1, 0),
            Node::None,
            Node::Cmux(1, 2, 1),
            Node::Copy,
            Node::Cmux(32, 2, 0),
            Node::None,
            Node::Cmux(0, 1, 0),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B24(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(56, 0, 1),
            Node::Cmux(56, 1, 0),
            Node::Cmux(24, 2, 1),
            Node::Cmux(24, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(55, 0, 1),
            Node::Cmux(23, 2, 1),
            Node::Cmux(23, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(54, 1, 0),
            Node::Cmux(22, 1, 2),
            Node::None,
            Node::Cmux(22, 2, 0),
            Node::Copy,
            Node::Cmux(53, 0, 2),
            Node::Copy,
            Node::Cmux(21, 0, 1),
            Node::None,
            Node::Cmux(21, 1, 2),
            Node::Copy,
            Node::Cmux(52, 0, 2),
            Node::Copy,
            Node::Cmux(20, 1, 2),
            Node::Cmux(20, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(51, 1, 0),
            Node::Cmux(19, 2, 0),
            Node::Cmux(19, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(50, 1, 0),
            Node::None,
            Node::Cmux(18, 2, 0),
            Node::Cmux(18, 1, 2),
            Node::Cmux(49, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(17, 2, 0),
            Node::Cmux(17, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(48, 0, 1),
            Node::Cmux(16, 0, 2),
            Node::Cmux(16, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 0, 1),
            Node::None,
            Node::Cmux(15, 2, 1),
            Node::Cmux(15, 0, 2),
            Node::Cmux(46, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(14, 2, 0),
            Node::None,
            Node::Cmux(14, 0, 1),
            Node::Copy,
            Node::Cmux(45, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(13, 0, 1),
            Node::Cmux(13, 1, 2),
            Node::Cmux(44, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(12, 0, 2),
            Node::None,
            Node::Cmux(12, 1, 0),
            Node::Copy,
            Node::Cmux(43, 2, 0),
            Node::Copy,
            Node::Cmux(11, 2, 1),
            Node::None,
            Node::Cmux(11, 1, 0),
            Node::Copy,
            Node::Cmux(42, 0, 2),
            Node::Copy,
            Node::Cmux(10, 1, 2),
            Node::Cmux(10, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 1, 0),
            Node::None,
            Node::Cmux(9, 1, 2),
            Node::Cmux(9, 2, 0),
            Node::Cmux(40, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(8, 0, 2),
            Node::None,
            Node::Cmux(8, 1, 0),
            Node::Copy,
            Node::Cmux(39, 2, 0),
            Node::Copy,
            Node::Cmux(7, 1, 0),
            Node::None,
            Node::Cmux(7, 2, 1),
            Node::Copy,
            Node::Cmux(38, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(6, 1, 0),
            Node::Cmux(6, 2, 1),
            Node::Cmux(37, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(5, 0, 1),
            Node::Cmux(5, 2, 0),
            Node::Cmux(36, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(4, 2, 0),
            Node::Cmux(4, 0, 1),
            Node::Cmux(35, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(3, 0, 2),
            Node::Cmux(3, 1, 0),
            Node::Cmux(34, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(2, 2, 0),
            Node::Cmux(2, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 0, 1),
            Node::Cmux(1, 2, 1),
            Node::Cmux(1, 0, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(32, 1, 0),
            Node::None,
            Node::Cmux(0, 1, 0),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B25(BitCircuit::new(
        [
            Node::Cmux(57, 0, 1),
            Node::None,
            Node::Cmux(57, 1, 0),
            Node::Cmux(25, 0, 2),
            Node::Cmux(25, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(56, 1, 0),
            Node::Cmux(24, 1, 2),
            Node::Cmux(24, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(55, 0, 1),
            Node::Cmux(23, 0, 2),
            Node::Cmux(23, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(54, 0, 1),
            Node::Cmux(22, 0, 2),
            Node::Cmux(22, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(53, 0, 1),
            Node::Cmux(21, 0, 2),
            Node::Cmux(21, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(52, 0, 1),
            Node::Cmux(20, 2, 1),
            Node::Cmux(20, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(51, 1, 0),
            Node::None,
            Node::Cmux(19, 1, 2),
            Node::Cmux(19, 2, 0),
            Node::Cmux(50, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Cmux(18, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(49, 0, 1),
            Node::Cmux(17, 2, 1),
            Node::None,
            Node::Cmux(17, 0, 2),
            Node::Copy,
            Node::Cmux(48, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(16, 2, 1),
            Node::Cmux(16, 1, 0),
            Node::Cmux(47, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(15, 0, 2),
            Node::Cmux(15, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 1, 0),
            Node::Cmux(14, 1, 2),
            Node::Cmux(14, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(45, 0, 1),
            Node::Cmux(13, 2, 1),
            Node::Cmux(13, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(44, 1, 0),
            Node::Cmux(12, 2, 0),
            Node::Cmux(12, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 1, 0),
            Node::Cmux(11, 2, 0),
            Node::Cmux(11, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(42, 1, 0),
            Node::Cmux(10, 2, 0),
            Node::Cmux(10, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 1, 0),
            Node::Cmux(9, 2, 0),
            Node::None,
            Node::Cmux(9, 1, 2),
            Node::Copy,
            Node::Cmux(40, 2, 0),
            Node::Copy,
            Node::Cmux(8, 2, 1),
            Node::Cmux(8, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 0, 1),
            Node::None,
            Node::Cmux(7, 0, 2),
            Node::Cmux(7, 2, 1),
            Node::Cmux(38, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(6, 0, 2),
            Node::Cmux(6, 1, 0),
            Node::Cmux(37, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::None,
            Node::Cmux(5, 2, 0),
            Node::Copy,
            Node::Cmux(36, 2, 0),
            Node::Copy,
            Node::Cmux(4, 2, 1),
            Node::Cmux(4, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(35, 0, 1),
            Node::None,
            Node::Cmux(3, 0, 2),
            Node::Cmux(3, 2, 1),
            Node::Cmux(34, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(2, 0, 2),
            Node::None,
            Node::Cmux(2, 1, 0),
            Node::Copy,
            Node::Cmux(33, 2, 0),
            Node::Copy,
            Node::Cmux(1, 2, 1),
            Node::Cmux(1, 1, 0),
            Node::None,
            Node::None,
            Node::Copy,
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B26(BitCircuit::new(
        [
            Node::Cmux(58, 0, 1),
            Node::Cmux(58, 1, 0),
            Node::None,
            Node::None,
            Node::Cmux(26, 1, 0),
            Node::Cmux(26, 0, 1),
            Node::Cmux(57, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(25, 1, 0),
            Node::Cmux(25, 0, 2),
            Node::Cmux(56, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(24, 1, 0),
            Node::Cmux(24, 0, 2),
            Node::Cmux(55, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(23, 0, 2),
            Node::Cmux(23, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(54, 1, 0),
            Node::None,
            Node::Cmux(22, 1, 2),
            Node::Cmux(22, 2, 0),
            Node::Cmux(53, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(21, 0, 2),
            Node::Cmux(21, 1, 0),
            Node::Cmux(52, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(20, 0, 1),
            Node::Cmux(20, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(51, 1, 0),
            Node::None,
            Node::Cmux(19, 2, 0),
            Node::Cmux(19, 1, 2),
            Node::Cmux(50, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(18, 0, 1),
            Node::None,
            Node::Cmux(18, 2, 0),
            Node::Copy,
            Node::Cmux(49, 2, 0),
            Node::Copy,
            Node::Cmux(17, 2, 1),
            Node::Cmux(17, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(48, 0, 1),
            Node::Cmux(16, 0, 2),
            Node::None,
            Node::Cmux(16, 2, 1),
            Node::Copy,
            Node::Cmux(47, 0, 2),
            Node::Copy,
            Node::Cmux(15, 0, 1),
            Node::None,
            Node::Cmux(15, 1, 2),
            Node::Copy,
            Node::Cmux(46, 0, 2),
            Node::Copy,
            Node::Cmux(14, 0, 1),
            Node::Cmux(14, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(45, 0, 1),
            Node::Cmux(13, 0, 2),
            Node::None,
            Node::Cmux(13, 2, 1),
            Node::Copy,
            Node::Cmux(44, 0, 2),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Cmux(12, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 0, 1),
            Node::None,
            Node::Cmux(11, 0, 2),
            Node::Cmux(11, 2, 1),
            Node::Cmux(42, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(10, 0, 2),
            Node::Cmux(10, 1, 0),
            Node::Cmux(41, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(9, 2, 0),
            Node::Cmux(9, 0, 1),
            Node::Cmux(40, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(8, 1, 0),
            Node::Cmux(8, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 0, 1),
            Node::Cmux(7, 0, 2),
            Node::Cmux(7, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 0, 1),
            Node::None,
            Node::Cmux(6, 2, 1),
            Node::Cmux(6, 0, 2),
            Node::Cmux(37, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(5, 0, 1),
            Node::None,
            Node::Cmux(5, 2, 0),
            Node::Copy,
            Node::Cmux(36, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(4, 2, 1),
            Node::Cmux(4, 1, 0),
            Node::Cmux(35, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::None,
            Node::Cmux(3, 0, 2),
            Node::Copy,
            Node::Cmux(34, 0, 2),
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
            Node::Cmux(2, 1, 2),
            Node::Copy,
            Node::Cmux(33, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(1, 1, 2),
            Node::Cmux(1, 0, 1),
            Node::Cmux(32, 2, 1),
            Node::Copy,
            Node::None,
            Node::Cmux(0, 0, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B27(BitCircuit::new(
        [
            Node::Cmux(59, 1, 0),
            Node::None,
            Node::Cmux(59, 0, 1),
            Node::Cmux(27, 2, 0),
            Node::None,
            Node::Cmux(27, 0, 2),
            Node::Copy,
            Node::Cmux(58, 2, 0),
            Node::Copy,
            Node::Cmux(26, 1, 0),
            Node::Cmux(26, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(57, 1, 0),
            Node::None,
            Node::Cmux(25, 2, 0),
            Node::Cmux(25, 1, 2),
            Node::Cmux(56, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(24, 2, 0),
            Node::None,
            Node::Cmux(24, 0, 1),
            Node::Copy,
            Node::Cmux(55, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(23, 1, 2),
            Node::Cmux(23, 0, 1),
            Node::Cmux(54, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(22, 0, 1),
            Node::None,
            Node::Cmux(22, 2, 0),
            Node::Copy,
            Node::Cmux(53, 2, 0),
            Node::Copy,
            Node::Cmux(21, 2, 1),
            Node::Cmux(21, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(52, 0, 1),
            Node::Cmux(20, 0, 2),
            Node::None,
            Node::Cmux(20, 2, 1),
            Node::Copy,
            Node::Cmux(51, 0, 2),
            Node::Copy,
            Node::Cmux(19, 1, 2),
            Node::Cmux(19, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(50, 1, 0),
            Node::Cmux(18, 1, 2),
            Node::Cmux(18, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(49, 0, 1),
            Node::Cmux(17, 2, 1),
            Node::None,
            Node::Cmux(17, 0, 2),
            Node::Copy,
            Node::Cmux(48, 2, 0),
            Node::Copy,
            Node::Cmux(16, 1, 0),
            Node::None,
            Node::Cmux(16, 2, 1),
            Node::Copy,
            Node::Cmux(47, 2, 0),
            Node::Copy,
            Node::Cmux(15, 2, 1),
            Node::Cmux(15, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 0, 1),
            Node::Cmux(14, 0, 2),
            Node::Cmux(14, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(45, 0, 1),
            Node::Cmux(13, 2, 1),
            Node::Cmux(13, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(44, 1, 0),
            Node::None,
            Node::Cmux(12, 1, 2),
            Node::Cmux(12, 2, 0),
            Node::Cmux(43, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(11, 1, 0),
            Node::Cmux(11, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(42, 0, 1),
            Node::Cmux(10, 0, 2),
            Node::Cmux(10, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 0, 1),
            Node::Cmux(9, 2, 1),
            Node::Cmux(9, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 1, 0),
            Node::None,
            Node::Cmux(8, 2, 0),
            Node::Cmux(8, 1, 2),
            Node::Cmux(39, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(7, 0, 1),
            Node::Cmux(7, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 1, 0),
            Node::Cmux(6, 1, 2),
            Node::None,
            Node::Cmux(6, 2, 0),
            Node::Copy,
            Node::Cmux(37, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(5, 1, 2),
            Node::Cmux(5, 0, 1),
            Node::Cmux(36, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(4, 2, 0),
            Node::Cmux(4, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(35, 0, 1),
            Node::Cmux(3, 0, 2),
            Node::Cmux(3, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::Cmux(2, 0, 2),
            Node::Cmux(2, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 0, 1),
            Node::Cmux(1, 0, 2),
            Node::Cmux(1, 2, 1),
            Node::None,
            Node::None,
            Node::Copy,
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B28(BitCircuit::new(
        [
            Node::Cmux(60, 0, 1),
            Node::Cmux(60, 1, 0),
            Node::None,
            Node::Cmux(28, 1, 0),
            Node::None,
            Node::Cmux(28, 0, 1),
            Node::Copy,
            Node::Cmux(59, 0, 2),
            Node::Copy,
            Node::Cmux(27, 1, 2),
            Node::Cmux(27, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(58, 1, 0),
            Node::None,
            Node::Cmux(26, 1, 2),
            Node::Cmux(26, 2, 0),
            Node::Cmux(57, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(25, 0, 2),
            Node::Cmux(25, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(56, 1, 0),
            Node::None,
            Node::Cmux(24, 1, 2),
            Node::Cmux(24, 2, 0),
            Node::Cmux(55, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(23, 0, 2),
            Node::Cmux(23, 1, 0),
            Node::Cmux(54, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(22, 0, 1),
            Node::Cmux(22, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(53, 1, 0),
            Node::Cmux(21, 1, 2),
            Node::Cmux(21, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(52, 0, 1),
            Node::Cmux(20, 2, 1),
            Node::None,
            Node::Cmux(20, 0, 2),
            Node::Copy,
            Node::Cmux(51, 2, 0),
            Node::Copy,
            Node::Cmux(19, 1, 0),
            Node::None,
            Node::Cmux(19, 2, 1),
            Node::Copy,
            Node::Cmux(50, 2, 0),
            Node::Copy,
            Node::Cmux(18, 1, 0),
            Node::Cmux(18, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(49, 1, 0),
            Node::Cmux(17, 1, 2),
            Node::None,
            Node::Cmux(17, 2, 0),
            Node::Copy,
            Node::Cmux(48, 0, 2),
            Node::Copy,
            Node::Cmux(16, 0, 1),
            Node::Cmux(16, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 0, 1),
            Node::Cmux(15, 2, 1),
            Node::Cmux(15, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 1, 0),
            Node::None,
            Node::Cmux(14, 2, 0),
            Node::Cmux(14, 1, 2),
            Node::Cmux(45, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(13, 0, 1),
            Node::None,
            Node::Cmux(13, 2, 0),
            Node::Copy,
            Node::Cmux(44, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(12, 2, 1),
            Node::Cmux(12, 1, 0),
            Node::Cmux(43, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(11, 0, 2),
            Node::Cmux(11, 1, 0),
            Node::Cmux(42, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(10, 0, 1),
            Node::None,
            Node::Cmux(10, 2, 0),
            Node::Copy,
            Node::Cmux(41, 2, 0),
            Node::Copy,
            Node::Cmux(9, 2, 1),
            Node::None,
            Node::Cmux(9, 1, 0),
            Node::Copy,
            Node::Cmux(40, 0, 2),
            Node::Copy,
            Node::Cmux(8, 0, 1),
            Node::Cmux(8, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 0, 1),
            Node::Cmux(7, 0, 2),
            Node::Cmux(7, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 0, 1),
            Node::None,
            Node::Cmux(6, 0, 2),
            Node::Cmux(6, 2, 1),
            Node::Cmux(37, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(5, 0, 2),
            Node::Cmux(5, 1, 0),
            Node::Cmux(36, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(4, 2, 0),
            Node::None,
            Node::Cmux(4, 0, 1),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(3, 1, 2),
            Node::Cmux(3, 0, 1),
            Node::Cmux(34, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(2, 0, 1),
            Node::None,
            Node::Cmux(2, 2, 0),
            Node::Copy,
            Node::Cmux(33, 2, 0),
            Node::Copy,
            Node::Cmux(1, 2, 1),
            Node::None,
            Node::Cmux(1, 1, 0),
            Node::Cmux(32, 0, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(0, 0, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B29(BitCircuit::new(
        [
            Node::Cmux(61, 0, 1),
            Node::None,
            Node::Cmux(61, 1, 0),
            Node::Cmux(29, 0, 2),
            Node::Cmux(29, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(60, 1, 0),
            Node::None,
            Node::Cmux(28, 2, 0),
            Node::Cmux(28, 1, 2),
            Node::Cmux(59, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(27, 2, 0),
            Node::Cmux(27, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(58, 0, 1),
            Node::Cmux(26, 2, 1),
            Node::Cmux(26, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(57, 1, 0),
            Node::Cmux(25, 2, 0),
            Node::Cmux(25, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(56, 1, 0),
            Node::Cmux(24, 1, 2),
            Node::None,
            Node::Cmux(24, 2, 0),
            Node::Copy,
            Node::Cmux(55, 0, 2),
            Node::Copy,
            Node::Cmux(23, 0, 1),
            Node::Cmux(23, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(54, 0, 1),
            Node::Cmux(22, 0, 2),
            Node::None,
            Node::Cmux(22, 2, 1),
            Node::Copy,
            Node::Cmux(53, 0, 2),
            Node::Copy,
            Node::Cmux(21, 1, 2),
            Node::None,
            Node::Cmux(21, 0, 1),
            Node::Copy,
            Node::Cmux(52, 2, 0),
            Node::Copy,
            Node::Cmux(20, 2, 1),
            Node::None,
            Node::Cmux(20, 1, 0),
            Node::Copy,
            Node::Cmux(51, 0, 2),
            Node::Copy,
            Node::Cmux(19, 1, 2),
            Node::Cmux(19, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(50, 1, 0),
            Node::Cmux(18, 2, 0),
            Node::None,
            Node::Cmux(18, 1, 2),
            Node::Copy,
            Node::Cmux(49, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(17, 2, 1),
            Node::Cmux(17, 1, 0),
            Node::Cmux(48, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(16, 0, 2),
            Node::Cmux(16, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 1, 0),
            Node::None,
            Node::Cmux(15, 2, 0),
            Node::Cmux(15, 1, 2),
            Node::Cmux(46, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(14, 0, 1),
            Node::Cmux(14, 2, 0),
            Node::Cmux(45, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(13, 2, 0),
            Node::Cmux(13, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(44, 0, 1),
            Node::Cmux(12, 2, 1),
            Node::None,
            Node::Cmux(12, 0, 2),
            Node::Copy,
            Node::Cmux(43, 2, 0),
            Node::Copy,
            Node::Cmux(11, 2, 1),
            Node::Cmux(11, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(42, 0, 1),
            Node::Cmux(10, 0, 2),
            Node::None,
            Node::Cmux(10, 2, 1),
            Node::Copy,
            Node::Cmux(41, 0, 2),
            Node::Copy,
            Node::Cmux(9, 0, 1),
            Node::Cmux(9, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 0, 1),
            Node::None,
            Node::Cmux(8, 0, 2),
            Node::Cmux(8, 2, 1),
            Node::Cmux(39, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(7, 0, 2),
            Node::Cmux(7, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 1, 0),
            Node::Cmux(6, 2, 0),
            Node::None,
            Node::Cmux(6, 1, 2),
            Node::Copy,
            Node::Cmux(37, 2, 0),
            Node::Copy,
            Node::Cmux(5, 2, 1),
            Node::Cmux(5, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 0, 1),
            Node::Cmux(4, 2, 1),
            Node::None,
            Node::Cmux(4, 0, 2),
            Node::Copy,
            Node::Cmux(35, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(3, 2, 1),
            Node::Cmux(3, 1, 0),
            Node::Cmux(34, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(2, 1, 0),
            Node::None,
            Node::Cmux(2, 0, 2),
            Node::Copy,
            Node::Cmux(33, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(1, 0, 1),
            Node::Cmux(1, 1, 2),
            Node::None,
            Node::Cmux(32, 1, 2),
            Node::Copy,
            Node::Cmux(0, 1, 2),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B30(BitCircuit::new(
        [
            Node::None,
            Node::Cmux(62, 1, 0),
            Node::Cmux(62, 0, 1),
            Node::Cmux(30, 1, 2),
            Node::None,
            Node::Cmux(30, 2, 1),
            Node::Copy,
            Node::Cmux(61, 0, 2),
            Node::Copy,
            Node::Cmux(29, 1, 2),
            Node::None,
            Node::Cmux(29, 0, 1),
            Node::Copy,
            Node::Cmux(60, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(28, 1, 0),
            Node::Cmux(28, 2, 1),
            Node::Cmux(59, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(27, 0, 1),
            Node::None,
            Node::Cmux(27, 2, 0),
            Node::Copy,
            Node::Cmux(58, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(26, 1, 0),
            Node::Cmux(26, 2, 1),
            Node::Cmux(57, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(25, 0, 1),
            Node::Cmux(25, 2, 0),
            Node::Cmux(56, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(24, 2, 0),
            Node::Cmux(24, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(55, 0, 1),
            Node::Cmux(23, 0, 2),
            Node::Cmux(23, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(54, 0, 1),
            Node::None,
            Node::Cmux(22, 2, 1),
            Node::Cmux(22, 0, 2),
            Node::Cmux(53, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(21, 0, 1),
            Node::Cmux(21, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(52, 1, 0),
            Node::Cmux(20, 2, 0),
            Node::Cmux(20, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(51, 1, 0),
            Node::Cmux(19, 2, 0),
            Node::None,
            Node::Cmux(19, 1, 2),
            Node::Copy,
            Node::Cmux(50, 2, 0),
            Node::Copy,
            Node::Cmux(18, 2, 1),
            Node::Cmux(18, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(49, 0, 1),
            Node::Cmux(17, 0, 2),
            Node::Cmux(17, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(48, 0, 1),
            Node::Cmux(16, 2, 1),
            Node::Cmux(16, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(47, 1, 0),
            Node::Cmux(15, 2, 0),
            Node::Cmux(15, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(46, 1, 0),
            Node::Cmux(14, 1, 2),
            Node::Cmux(14, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(45, 0, 1),
            Node::Cmux(13, 0, 2),
            Node::None,
            Node::Cmux(13, 2, 1),
            Node::Copy,
            Node::Cmux(44, 0, 2),
            Node::Copy,
            Node::Cmux(12, 0, 1),
            Node::Cmux(12, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(43, 0, 1),
            Node::Cmux(11, 2, 1),
            Node::None,
            Node::Cmux(11, 0, 2),
            Node::Copy,
            Node::Cmux(42, 2, 0),
            Node::Copy,
            Node::Cmux(10, 2, 1),
            Node::Cmux(10, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 0, 1),
            Node::Cmux(9, 0, 2),
            Node::Cmux(9, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 0, 1),
            Node::Cmux(8, 0, 2),
            Node::Cmux(8, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(39, 0, 1),
            Node::Cmux(7, 0, 2),
            Node::None,
            Node::Cmux(7, 2, 1),
            Node::Copy,
            Node::Cmux(38, 0, 2),
            Node::Copy,
            Node::Cmux(6, 0, 1),
            Node::Cmux(6, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(37, 0, 1),
            Node::Cmux(5, 0, 2),
            Node::Cmux(5, 2, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 0, 1),
            Node::None,
            Node::Cmux(4, 0, 2),
            Node::Cmux(4, 2, 1),
            Node::Cmux(35, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(3, 1, 0),
            Node::None,
            Node::Cmux(3, 0, 2),
            Node::Copy,
            Node::Cmux(34, 0, 2),
            Node::Copy,
            Node::Cmux(2, 1, 2),
            Node::Cmux(2, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 1, 0),
            Node::Cmux(1, 1, 2),
            Node::Cmux(1, 2, 0),
            Node::None,
            Node::None,
            Node::Copy,
            Node::Cmux(32, 0, 1),
            Node::Cmux(0, 2, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B31(BitCircuit::new(
        [
            Node::Cmux(63, 1, 0),
            Node::None,
            Node::Cmux(63, 0, 1),
            Node::Cmux(31, 0, 2),
            Node::None,
            Node::Cmux(31, 2, 0),
            Node::Copy,
            Node::Cmux(62, 0, 2),
            Node::Copy,
            Node::None,
            Node::Cmux(30, 1, 2),
            Node::Cmux(30, 0, 1),
            Node::Cmux(61, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(29, 0, 1),
            Node::None,
            Node::Cmux(29, 2, 0),
            Node::Copy,
            Node::Cmux(60, 2, 0),
            Node::Copy,
            Node::Cmux(28, 2, 1),
            Node::Cmux(28, 1, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(59, 0, 1),
            Node::Cmux(27, 0, 2),
            Node::None,
            Node::Cmux(27, 2, 1),
            Node::Copy,
            Node::Cmux(58, 0, 2),
            Node::Copy,
            Node::Cmux(26, 1, 2),
            Node::Cmux(26, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(57, 1, 0),
            Node::None,
            Node::Cmux(25, 2, 0),
            Node::Cmux(25, 1, 2),
            Node::Cmux(56, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(24, 0, 1),
            Node::Cmux(24, 2, 0),
            Node::Cmux(55, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(23, 0, 1),
            Node::Cmux(23, 2, 0),
            Node::Cmux(54, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(22, 0, 1),
            Node::Cmux(22, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(53, 1, 0),
            Node::None,
            Node::Cmux(21, 2, 0),
            Node::Cmux(21, 1, 2),
            Node::Cmux(52, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(20, 0, 1),
            Node::Cmux(20, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(51, 1, 0),
            Node::None,
            Node::Cmux(19, 2, 0),
            Node::Cmux(19, 1, 2),
            Node::Cmux(50, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(18, 2, 0),
            Node::Cmux(18, 0, 1),
            Node::Cmux(49, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::Cmux(17, 0, 2),
            Node::None,
            Node::Cmux(17, 1, 0),
            Node::Copy,
            Node::Cmux(48, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(16, 1, 0),
            Node::Cmux(16, 2, 1),
            Node::Cmux(47, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(15, 0, 1),
            Node::Cmux(15, 2, 0),
            Node::Cmux(46, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(14, 2, 0),
            Node::Cmux(14, 0, 1),
            Node::Cmux(45, 1, 2),
            Node::Copy,
            Node::Copy,
            Node::None,
            Node::Cmux(13, 0, 2),
            Node::Cmux(13, 1, 0),
            Node::Cmux(44, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(12, 2, 0),
            Node::None,
            Node::Cmux(12, 0, 1),
            Node::Copy,
            Node::Cmux(43, 0, 2),
            Node::Copy,
            Node::Cmux(11, 0, 1),
            Node::None,
            Node::Cmux(11, 1, 2),
            Node::Copy,
            Node::Cmux(42, 0, 2),
            Node::Copy,
            Node::Cmux(10, 1, 2),
            Node::Cmux(10, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(41, 1, 0),
            Node::Cmux(9, 2, 0),
            Node::Cmux(9, 1, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(40, 1, 0),
            Node::Cmux(8, 1, 2),
            Node::None,
            Node::Cmux(8, 2, 0),
            Node::Copy,
            Node::Cmux(39, 0, 2),
            Node::Copy,
            Node::Cmux(7, 1, 2),
            Node::Cmux(7, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(38, 1, 0),
            Node::Cmux(6, 1, 2),
            Node::Cmux(6, 2, 0),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(37, 0, 1),
            Node::Cmux(5, 2, 1),
            Node::Cmux(5, 0, 2),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(36, 1, 0),
            Node::Cmux(4, 2, 0),
            Node::None,
            Node::Cmux(4, 1, 2),
            Node::Copy,
            Node::Cmux(35, 2, 0),
            Node::Copy,
            Node::None,
            Node::Cmux(3, 1, 0),
            Node::Cmux(3, 2, 1),
            Node::Cmux(34, 2, 1),
            Node::Copy,
            Node::Copy,
            Node::Cmux(2, 2, 0),
            Node::Cmux(2, 0, 1),
            Node::None,
            Node::Copy,
            Node::Copy,
            Node::Cmux(33, 0, 1),
            Node::Cmux(1, 2, 1),
            Node::Cmux(1, 0, 2),
            Node::None,
            Node::Copy,
            Node::Cmux(32, 1, 0),
            Node::None,
            Node::Cmux(0, 1, 0),
            Node::None,
            Node::None,
        ],
        3,
    )),
]);
