use crate::tfhe::bdd_arithmetic::{BitCircuit, BitCircuitInfo, Circuit, GetBitCircuitInfo, Node};
pub(crate) enum AnyBitCircuit {
    B0(BitCircuit<192>),
    B1(BitCircuit<186>),
    B2(BitCircuit<180>),
    B3(BitCircuit<174>),
    B4(BitCircuit<168>),
    B5(BitCircuit<162>),
    B6(BitCircuit<156>),
    B7(BitCircuit<150>),
    B8(BitCircuit<144>),
    B9(BitCircuit<138>),
    B10(BitCircuit<132>),
    B11(BitCircuit<126>),
    B12(BitCircuit<120>),
    B13(BitCircuit<114>),
    B14(BitCircuit<108>),
    B15(BitCircuit<102>),
    B16(BitCircuit<96>),
    B17(BitCircuit<90>),
    B18(BitCircuit<84>),
    B19(BitCircuit<78>),
    B20(BitCircuit<72>),
    B21(BitCircuit<66>),
    B22(BitCircuit<60>),
    B23(BitCircuit<54>),
    B24(BitCircuit<48>),
    B25(BitCircuit<42>),
    B26(BitCircuit<36>),
    B27(BitCircuit<30>),
    B28(BitCircuit<24>),
    B29(BitCircuit<18>),
    B30(BitCircuit<12>),
    B31(BitCircuit<2>),
}
impl BitCircuitInfo for AnyBitCircuit {
    fn info(&self) -> (&[Node], usize) {
        match self {
            AnyBitCircuit::B0(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B1(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B2(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B3(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B4(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B5(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B6(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B7(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B8(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B9(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B10(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B11(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B12(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B13(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B14(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B15(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B16(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B17(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B18(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B19(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B20(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B21(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B22(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B23(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B24(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B25(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B26(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B27(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B28(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B29(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B30(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
            AnyBitCircuit::B31(bit_circuit) => (bit_circuit.nodes.as_ref(), bit_circuit.max_inter_state),
        }
    }
}

impl GetBitCircuitInfo<u32> for Circuit<AnyBitCircuit, 32usize> {
    fn input_size(&self) -> usize {
        2 * u32::BITS as usize
    }
    fn output_size(&self) -> usize {
        u32::BITS as usize
    }
    fn get_circuit(&self, bit: usize) -> (&[Node], usize) {
        self.0[bit].info()
    }
}

pub(crate) static OUTPUT_CIRCUITS: Circuit<AnyBitCircuit, 32usize> = Circuit([
    AnyBitCircuit::B0(BitCircuit::new(
        [
            Node::Cmux(15, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(6, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(5, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::Cmux(3, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(7, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(1, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(0, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(4, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(36, 14, 24),
            Node::Cmux(36, 1, 28),
            Node::Cmux(36, 17, 16),
            Node::Cmux(36, 7, 12),
            Node::Cmux(36, 30, 0),
            Node::Cmux(36, 11, 25),
            Node::None,
            Node::None,
            Node::Cmux(36, 22, 15),
            Node::Cmux(36, 21, 4),
            Node::None,
            Node::None,
            Node::Cmux(36, 18, 8),
            Node::Cmux(36, 5, 20),
            Node::None,
            Node::None,
            Node::Cmux(36, 27, 29),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 31, 6),
            Node::None,
            Node::None,
            Node::Cmux(36, 10, 23),
            Node::Cmux(36, 26, 3),
            Node::None,
            Node::Cmux(36, 13, 9),
            Node::Cmux(36, 2, 19),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 24, 23),
            Node::None,
            Node::None,
            Node::Cmux(35, 13, 12),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 26, 5),
            Node::Cmux(35, 4, 27),
            Node::Cmux(35, 0, 1),
            Node::None,
            Node::Cmux(35, 16, 2),
            Node::None,
            Node::Cmux(35, 3, 8),
            Node::None,
            Node::None,
            Node::Cmux(35, 20, 9),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 9, 12),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 10, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 17, 14),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 3, 0),
            Node::None,
            Node::Cmux(33, 24, 13),
            Node::Cmux(33, 2, 31),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 2, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        32,
    )),
    AnyBitCircuit::B1(BitCircuit::new(
        [
            Node::Cmux(25, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(5, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(1, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(6, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(7, 1, 0),
            Node::Cmux(4, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(3, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(36, 5, 21),
            Node::Cmux(36, 11, 8),
            Node::Cmux(36, 27, 22),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 18, 25),
            Node::Cmux(36, 30, 10),
            Node::Cmux(36, 19, 1),
            Node::None,
            Node::Cmux(36, 29, 3),
            Node::Cmux(36, 23, 13),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 24, 7),
            Node::Cmux(36, 0, 2),
            Node::None,
            Node::None,
            Node::Cmux(36, 6, 9),
            Node::Cmux(36, 28, 12),
            Node::Cmux(36, 16, 14),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 18, 15),
            Node::None,
            Node::Cmux(36, 26, 4),
            Node::None,
            Node::Cmux(36, 17, 20),
            Node::None,
            Node::None,
            Node::Cmux(35, 26, 2),
            Node::None,
            Node::None,
            Node::Cmux(35, 28, 0),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 8, 11),
            Node::Cmux(35, 1, 10),
            Node::Cmux(35, 21, 30),
            Node::None,
            Node::None,
            Node::Cmux(35, 6, 20),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 16, 15),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 19, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 17, 25),
            Node::None,
            Node::Cmux(34, 29, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 2, 16),
            Node::Cmux(34, 21, 18),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 22, 6),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 21, 8),
            Node::Cmux(32, 30, 10),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        31,
    )),
    AnyBitCircuit::B2(BitCircuit::new(
        [
            Node::Cmux(28, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(2, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(3, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(7, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(5, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(4, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(6, 1, 0),
            Node::Cmux(36, 16, 13),
            Node::Cmux(36, 5, 8),
            Node::None,
            Node::None,
            Node::Cmux(36, 3, 26),
            Node::None,
            Node::Cmux(36, 25, 12),
            Node::Cmux(36, 2, 15),
            Node::None,
            Node::Cmux(36, 6, 18),
            Node::Cmux(36, 23, 10),
            Node::Cmux(36, 16, 9),
            Node::None,
            Node::Cmux(36, 22, 29),
            Node::None,
            Node::Cmux(36, 0, 11),
            Node::Cmux(36, 27, 24),
            Node::None,
            Node::Cmux(36, 17, 7),
            Node::None,
            Node::None,
            Node::Cmux(36, 28, 21),
            Node::None,
            Node::Cmux(36, 16, 14),
            Node::None,
            Node::None,
            Node::Cmux(36, 4, 1),
            Node::None,
            Node::None,
            Node::Cmux(36, 20, 19),
            Node::None,
            Node::Cmux(35, 1, 7),
            Node::Cmux(35, 15, 4),
            Node::None,
            Node::None,
            Node::Cmux(35, 6, 13),
            Node::None,
            Node::Cmux(35, 11, 16),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 23, 9),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 29, 18),
            Node::None,
            Node::Cmux(35, 0, 10),
            Node::None,
            Node::None,
            Node::Cmux(35, 26, 21),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 7, 26),
            Node::None,
            Node::None,
            Node::Cmux(34, 5, 21),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 13, 1),
            Node::Cmux(34, 23, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 22, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 5, 21),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 16, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        30,
    )),
    AnyBitCircuit::B3(BitCircuit::new(
        [
            Node::Cmux(29, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(3, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(5, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(4, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(6, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(7, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(36, 1, 2),
            Node::Cmux(36, 7, 6),
            Node::Cmux(36, 28, 16),
            Node::Cmux(36, 28, 24),
            Node::Cmux(36, 25, 26),
            Node::Cmux(36, 28, 22),
            Node::None,
            Node::None,
            Node::Cmux(36, 28, 10),
            Node::Cmux(36, 3, 4),
            Node::Cmux(36, 17, 5),
            Node::Cmux(36, 19, 14),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 20, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 18, 9),
            Node::Cmux(36, 0, 8),
            Node::Cmux(36, 12, 13),
            Node::None,
            Node::Cmux(36, 21, 23),
            Node::None,
            Node::Cmux(36, 27, 15),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 8, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 24, 15),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 5, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 23, 9),
            Node::None,
            Node::Cmux(35, 22, 0),
            Node::Cmux(35, 3, 26),
            Node::None,
            Node::Cmux(35, 2, 10),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 4, 28),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 3, 17),
            Node::Cmux(34, 20, 19),
            Node::Cmux(34, 22, 26),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 12, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 12, 18),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 10, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 7, 20),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        29,
    )),
    AnyBitCircuit::B4(BitCircuit::new(
        [
            Node::Cmux(23, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(4, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(6, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(5, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(7, 1, 0),
            Node::None,
            Node::Cmux(36, 12, 6),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 19, 15),
            Node::Cmux(36, 3, 2),
            Node::None,
            Node::Cmux(36, 7, 8),
            Node::None,
            Node::Cmux(36, 19, 26),
            Node::None,
            Node::Cmux(36, 19, 22),
            Node::None,
            Node::Cmux(36, 19, 9),
            Node::None,
            Node::Cmux(36, 20, 21),
            Node::Cmux(36, 17, 11),
            Node::None,
            Node::Cmux(36, 13, 1),
            Node::Cmux(36, 23, 10),
            Node::None,
            Node::Cmux(36, 18, 4),
            Node::Cmux(36, 0, 27),
            Node::None,
            Node::Cmux(36, 14, 16),
            Node::Cmux(36, 19, 25),
            Node::Cmux(36, 24, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 19, 8),
            Node::None,
            Node::None,
            Node::Cmux(35, 10, 16),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 14, 17),
            Node::Cmux(35, 26, 20),
            Node::Cmux(35, 5, 1),
            Node::Cmux(35, 12, 23),
            Node::None,
            Node::Cmux(35, 22, 6),
            Node::None,
            Node::Cmux(35, 27, 25),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 6, 20),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 15, 3),
            Node::None,
            Node::None,
            Node::Cmux(34, 17, 18),
            Node::Cmux(34, 16, 22),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 22, 23),
            Node::None,
            Node::Cmux(33, 19, 3),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 6, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        28,
    )),
    AnyBitCircuit::B5(BitCircuit::new(
        [
            Node::Cmux(6, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(7, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(5, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(36, 13, 6),
            Node::None,
            Node::Cmux(36, 13, 12),
            Node::Cmux(36, 23, 17),
            Node::Cmux(36, 8, 19),
            Node::Cmux(36, 13, 7),
            Node::None,
            Node::None,
            Node::Cmux(36, 25, 9),
            Node::Cmux(36, 21, 22),
            Node::Cmux(36, 13, 15),
            Node::Cmux(36, 1, 4),
            Node::Cmux(36, 11, 10),
            Node::Cmux(36, 13, 16),
            Node::None,
            Node::None,
            Node::Cmux(36, 13, 26),
            Node::Cmux(36, 14, 5),
            Node::None,
            Node::Cmux(36, 24, 3),
            Node::None,
            Node::Cmux(36, 20, 0),
            Node::Cmux(36, 18, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 16, 12),
            Node::None,
            Node::Cmux(35, 8, 21),
            Node::None,
            Node::Cmux(35, 13, 17),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 3, 4),
            Node::None,
            Node::None,
            Node::Cmux(35, 0, 22),
            Node::None,
            Node::None,
            Node::Cmux(35, 2, 9),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 10, 19),
            Node::None,
            Node::Cmux(35, 5, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 23, 12),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 25, 15),
            Node::None,
            Node::None,
            Node::Cmux(34, 7, 18),
            Node::Cmux(34, 3, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 17, 9),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 20, 21),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 20, 6),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        27,
    )),
    AnyBitCircuit::B6(BitCircuit::new(
        [
            Node::Cmux(16, 1, 0),
            Node::Cmux(7, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(6, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(36, 4, 25),
            Node::Cmux(36, 22, 3),
            Node::None,
            Node::None,
            Node::Cmux(36, 6, 9),
            Node::Cmux(36, 24, 2),
            Node::Cmux(36, 22, 7),
            Node::None,
            Node::None,
            Node::Cmux(36, 22, 12),
            Node::Cmux(36, 22, 14),
            Node::Cmux(36, 21, 16),
            Node::Cmux(36, 11, 20),
            Node::Cmux(36, 22, 19),
            Node::Cmux(36, 22, 18),
            Node::Cmux(36, 15, 1),
            Node::None,
            Node::None,
            Node::Cmux(36, 22, 0),
            Node::None,
            Node::Cmux(36, 13, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 17, 10),
            Node::Cmux(36, 23, 8),
            Node::None,
            Node::None,
            Node::Cmux(35, 0, 4),
            Node::Cmux(35, 14, 5),
            Node::None,
            Node::None,
            Node::Cmux(35, 10, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 9, 25),
            Node::Cmux(35, 1, 12),
            Node::None,
            Node::Cmux(35, 13, 15),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 6, 24),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 18, 20),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 12, 15),
            Node::None,
            Node::Cmux(34, 3, 23),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 6, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 13, 19),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 7, 11),
            Node::None,
            Node::None,
            Node::Cmux(33, 24, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 16, 13),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        26,
    )),
    AnyBitCircuit::B7(BitCircuit::new(
        [
            Node::Cmux(9, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(7, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(36, 24, 2),
            Node::Cmux(36, 24, 20),
            Node::Cmux(36, 22, 11),
            Node::Cmux(36, 13, 10),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 24, 19),
            Node::None,
            Node::Cmux(36, 24, 16),
            Node::Cmux(36, 17, 1),
            Node::None,
            Node::Cmux(36, 18, 6),
            Node::None,
            Node::Cmux(36, 24, 23),
            Node::Cmux(36, 24, 5),
            Node::Cmux(36, 9, 4),
            Node::Cmux(36, 12, 7),
            Node::None,
            Node::None,
            Node::Cmux(36, 21, 0),
            Node::Cmux(36, 3, 15),
            Node::Cmux(36, 24, 8),
            Node::Cmux(36, 24, 14),
            Node::Cmux(35, 24, 18),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 8, 17),
            Node::None,
            Node::Cmux(35, 10, 3),
            Node::Cmux(35, 0, 11),
            Node::Cmux(35, 15, 21),
            Node::None,
            Node::None,
            Node::Cmux(35, 1, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 16, 13),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 23, 22),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 24, 9),
            Node::None,
            Node::None,
            Node::Cmux(34, 5, 0),
            Node::Cmux(34, 8, 20),
            Node::Cmux(34, 7, 12),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 12, 10),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 7, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 0, 12),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        25,
    )),
    AnyBitCircuit::B8(BitCircuit::new(
        [
            Node::Cmux(28, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(8, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(36, 10, 13),
            Node::Cmux(36, 4, 15),
            Node::Cmux(36, 10, 14),
            Node::Cmux(36, 10, 7),
            Node::Cmux(36, 19, 17),
            Node::Cmux(36, 10, 12),
            Node::Cmux(36, 10, 11),
            Node::None,
            Node::Cmux(36, 20, 9),
            Node::Cmux(36, 0, 16),
            Node::Cmux(36, 3, 2),
            Node::Cmux(36, 21, 22),
            Node::None,
            Node::Cmux(36, 10, 18),
            Node::Cmux(36, 10, 23),
            Node::None,
            Node::Cmux(36, 10, 6),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 10, 5),
            Node::None,
            Node::None,
            Node::Cmux(36, 1, 8),
            Node::None,
            Node::None,
            Node::Cmux(35, 14, 2),
            Node::None,
            Node::Cmux(35, 6, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 20, 9),
            Node::Cmux(35, 5, 8),
            Node::Cmux(35, 16, 11),
            Node::None,
            Node::Cmux(35, 0, 4),
            Node::None,
            Node::None,
            Node::Cmux(35, 13, 23),
            Node::None,
            Node::None,
            Node::Cmux(35, 3, 10),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 9, 10),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 11, 13),
            Node::None,
            Node::Cmux(34, 2, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 16, 19),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 22, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 15, 13),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 14, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        24,
    )),
    AnyBitCircuit::B9(BitCircuit::new(
        [
            Node::Cmux(17, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(9, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(36, 16, 19),
            Node::Cmux(36, 1, 9),
            Node::Cmux(36, 16, 14),
            Node::Cmux(36, 16, 11),
            Node::Cmux(36, 4, 2),
            Node::Cmux(36, 16, 18),
            Node::Cmux(36, 3, 17),
            Node::None,
            Node::Cmux(36, 16, 0),
            Node::Cmux(36, 12, 15),
            Node::None,
            Node::Cmux(36, 8, 5),
            Node::Cmux(36, 16, 7),
            Node::Cmux(36, 10, 22),
            Node::None,
            Node::Cmux(36, 16, 6),
            Node::Cmux(36, 16, 20),
            Node::Cmux(36, 16, 13),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(36, 16, 21),
            Node::None,
            Node::Cmux(35, 8, 6),
            Node::None,
            Node::Cmux(35, 0, 9),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 16, 13),
            Node::None,
            Node::None,
            Node::Cmux(35, 17, 1),
            Node::Cmux(35, 3, 15),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 2, 4),
            Node::None,
            Node::Cmux(35, 5, 12),
            Node::None,
            Node::Cmux(35, 21, 11),
            Node::None,
            Node::Cmux(34, 22, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 12, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 20, 18),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 2, 0),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 13, 1),
            Node::Cmux(33, 5, 18),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 10, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        23,
    )),
    AnyBitCircuit::B10(BitCircuit::new(
        [
            Node::Cmux(30, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(10, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(36, 14, 18),
            Node::Cmux(36, 14, 2),
            Node::None,
            Node::Cmux(36, 15, 13),
            Node::Cmux(36, 14, 9),
            Node::Cmux(36, 16, 6),
            Node::Cmux(36, 14, 19),
            Node::None,
            Node::Cmux(36, 14, 3),
            Node::None,
            Node::None,
            Node::Cmux(36, 7, 5),
            Node::Cmux(36, 14, 11),
            Node::Cmux(36, 14, 12),
            Node::None,
            Node::Cmux(36, 14, 20),
            Node::Cmux(36, 0, 4),
            Node::None,
            Node::Cmux(36, 14, 10),
            Node::Cmux(36, 1, 17),
            Node::Cmux(36, 14, 21),
            Node::Cmux(36, 14, 8),
            Node::None,
            Node::None,
            Node::Cmux(35, 8, 0),
            Node::None,
            Node::Cmux(35, 15, 5),
            Node::None,
            Node::Cmux(35, 6, 18),
            Node::None,
            Node::Cmux(35, 13, 1),
            Node::None,
            Node::Cmux(35, 20, 19),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 21, 16),
            Node::None,
            Node::None,
            Node::Cmux(35, 4, 3),
            Node::Cmux(35, 12, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 8, 19),
            Node::Cmux(34, 16, 20),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 6, 10),
            Node::Cmux(34, 2, 4),
            Node::None,
            Node::Cmux(33, 19, 10),
            Node::None,
            Node::None,
            Node::Cmux(33, 20, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 0, 3),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        22,
    )),
    AnyBitCircuit::B11(BitCircuit::new(
        [
            Node::Cmux(31, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(11, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(36, 0, 3),
            Node::Cmux(36, 9, 11),
            Node::None,
            Node::Cmux(36, 0, 14),
            Node::Cmux(36, 0, 7),
            Node::Cmux(36, 13, 17),
            Node::None,
            Node::Cmux(36, 0, 19),
            Node::Cmux(36, 0, 16),
            Node::Cmux(36, 0, 15),
            Node::Cmux(36, 0, 4),
            Node::None,
            Node::None,
            Node::Cmux(36, 10, 6),
            Node::Cmux(36, 0, 12),
            Node::Cmux(36, 0, 5),
            Node::Cmux(36, 0, 8),
            Node::None,
            Node::Cmux(36, 0, 1),
            Node::Cmux(36, 0, 18),
            Node::Cmux(36, 20, 2),
            Node::None,
            Node::Cmux(35, 4, 14),
            Node::Cmux(35, 9, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 0, 1),
            Node::None,
            Node::Cmux(35, 8, 5),
            Node::None,
            Node::Cmux(35, 15, 20),
            Node::Cmux(35, 19, 18),
            Node::None,
            Node::None,
            Node::Cmux(35, 10, 3),
            Node::None,
            Node::None,
            Node::Cmux(35, 16, 13),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 1, 18),
            Node::None,
            Node::None,
            Node::Cmux(34, 2, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 15, 9),
            Node::Cmux(34, 12, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 7, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 12, 11),
            Node::None,
            Node::None,
            Node::Cmux(32, 6, 18),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        21,
    )),
    AnyBitCircuit::B12(BitCircuit::new(
        [
            Node::Cmux(31, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(12, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(36, 0, 13),
            Node::Cmux(36, 0, 7),
            Node::Cmux(36, 0, 17),
            Node::None,
            Node::Cmux(36, 0, 5),
            Node::None,
            Node::Cmux(36, 0, 2),
            Node::Cmux(36, 0, 8),
            Node::Cmux(36, 0, 14),
            Node::Cmux(36, 0, 18),
            Node::Cmux(36, 0, 10),
            Node::Cmux(36, 0, 16),
            Node::None,
            Node::Cmux(36, 3, 6),
            Node::Cmux(36, 0, 19),
            Node::Cmux(36, 9, 1),
            Node::None,
            Node::Cmux(36, 15, 11),
            Node::Cmux(36, 0, 12),
            Node::Cmux(36, 0, 4),
            Node::None,
            Node::Cmux(35, 18, 17),
            Node::None,
            Node::Cmux(35, 19, 0),
            Node::None,
            Node::Cmux(35, 8, 11),
            Node::Cmux(35, 1, 13),
            Node::Cmux(35, 6, 15),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 9, 2),
            Node::None,
            Node::None,
            Node::Cmux(35, 14, 10),
            Node::Cmux(35, 7, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 14, 6),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 17, 1),
            Node::Cmux(34, 5, 18),
            Node::Cmux(34, 3, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 8, 6),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 7, 2),
            Node::None,
            Node::Cmux(32, 18, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        20,
    )),
    AnyBitCircuit::B13(BitCircuit::new(
        [
            Node::Cmux(19, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(13, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(36, 6, 1),
            Node::Cmux(36, 6, 11),
            Node::Cmux(36, 6, 9),
            Node::Cmux(36, 6, 16),
            Node::Cmux(36, 6, 4),
            Node::Cmux(36, 6, 8),
            Node::Cmux(36, 6, 15),
            Node::Cmux(36, 17, 12),
            Node::Cmux(36, 6, 2),
            Node::Cmux(36, 6, 14),
            Node::None,
            Node::Cmux(36, 6, 5),
            Node::Cmux(36, 10, 18),
            Node::None,
            Node::Cmux(36, 6, 0),
            Node::None,
            Node::Cmux(36, 6, 3),
            Node::Cmux(36, 6, 13),
            Node::Cmux(36, 6, 7),
            Node::None,
            Node::Cmux(35, 5, 14),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 3, 16),
            Node::None,
            Node::Cmux(35, 9, 12),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 2, 7),
            Node::Cmux(35, 18, 0),
            Node::Cmux(35, 4, 11),
            Node::Cmux(35, 17, 6),
            Node::Cmux(35, 8, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 15, 13),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 1, 6),
            Node::Cmux(34, 14, 8),
            Node::None,
            Node::Cmux(34, 16, 12),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 9, 12),
            Node::Cmux(33, 2, 10),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 2, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        19,
    )),
    AnyBitCircuit::B14(BitCircuit::new(
        [
            Node::Cmux(26, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(14, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(36, 8, 5),
            Node::Cmux(36, 8, 16),
            Node::Cmux(36, 8, 15),
            Node::Cmux(36, 8, 3),
            Node::Cmux(36, 8, 17),
            Node::Cmux(36, 8, 10),
            Node::Cmux(36, 8, 6),
            Node::Cmux(36, 8, 11),
            Node::Cmux(36, 8, 1),
            Node::Cmux(36, 8, 7),
            Node::Cmux(36, 8, 9),
            Node::None,
            Node::Cmux(36, 8, 12),
            Node::Cmux(36, 8, 2),
            Node::Cmux(36, 4, 13),
            Node::None,
            Node::Cmux(36, 8, 14),
            Node::Cmux(36, 8, 0),
            Node::None,
            Node::None,
            Node::Cmux(35, 3, 14),
            Node::None,
            Node::Cmux(35, 1, 16),
            Node::Cmux(35, 0, 10),
            Node::None,
            Node::Cmux(35, 4, 12),
            Node::Cmux(35, 13, 9),
            Node::None,
            Node::None,
            Node::Cmux(35, 17, 5),
            Node::None,
            Node::None,
            Node::Cmux(35, 2, 7),
            Node::None,
            Node::None,
            Node::Cmux(35, 6, 8),
            Node::None,
            Node::Cmux(34, 11, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 14, 17),
            Node::None,
            Node::None,
            Node::Cmux(34, 7, 4),
            Node::None,
            Node::None,
            Node::Cmux(34, 8, 5),
            Node::None,
            Node::None,
            Node::Cmux(33, 9, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 15, 12),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 13, 0),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        18,
    )),
    AnyBitCircuit::B15(BitCircuit::new(
        [
            Node::Cmux(27, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(15, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::None,
            Node::Cmux(36, 2, 1),
            Node::Cmux(36, 2, 10),
            Node::Cmux(36, 2, 12),
            Node::Cmux(36, 2, 4),
            Node::Cmux(36, 2, 5),
            Node::Cmux(36, 2, 0),
            Node::Cmux(36, 2, 14),
            Node::Cmux(36, 2, 16),
            Node::Cmux(36, 2, 9),
            Node::Cmux(36, 2, 11),
            Node::Cmux(36, 2, 13),
            Node::Cmux(36, 2, 8),
            Node::Cmux(36, 2, 6),
            Node::Cmux(36, 2, 3),
            Node::Cmux(36, 2, 15),
            Node::Cmux(36, 2, 7),
            Node::Cmux(35, 14, 12),
            Node::None,
            Node::None,
            Node::Cmux(35, 3, 2),
            Node::None,
            Node::Cmux(35, 15, 5),
            Node::Cmux(35, 16, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 10, 13),
            Node::Cmux(35, 1, 11),
            Node::None,
            Node::Cmux(35, 9, 8),
            Node::Cmux(35, 6, 4),
            Node::Cmux(34, 5, 13),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 16, 6),
            Node::Cmux(34, 12, 0),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 15, 3),
            Node::None,
            Node::Cmux(33, 9, 0),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 15, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 0, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        17,
    )),
    AnyBitCircuit::B16(BitCircuit::new(
        [
            Node::Cmux(18, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(16, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(36, 9, 13),
            Node::Cmux(36, 9, 0),
            Node::Cmux(36, 9, 2),
            Node::Cmux(36, 9, 1),
            Node::Cmux(36, 9, 7),
            Node::Cmux(36, 9, 5),
            Node::Cmux(36, 9, 10),
            Node::Cmux(36, 9, 12),
            Node::Cmux(36, 9, 6),
            Node::Copy,
            Node::Cmux(36, 9, 11),
            Node::Cmux(36, 9, 4),
            Node::Cmux(36, 9, 14),
            Node::Cmux(36, 9, 15),
            Node::Cmux(36, 9, 3),
            Node::Cmux(36, 9, 8),
            Node::None,
            Node::Cmux(35, 14, 12),
            Node::None,
            Node::Cmux(35, 13, 0),
            Node::None,
            Node::Cmux(35, 10, 4),
            Node::Cmux(35, 9, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 3, 15),
            Node::None,
            Node::Cmux(35, 8, 2),
            Node::Cmux(35, 6, 1),
            Node::Cmux(35, 7, 5),
            Node::None,
            Node::Cmux(34, 1, 5),
            Node::None,
            Node::Cmux(34, 13, 11),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 6, 15),
            Node::None,
            Node::Cmux(34, 3, 14),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 15, 1),
            Node::None,
            Node::Cmux(33, 13, 3),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 10, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        16,
    )),
    AnyBitCircuit::B17(BitCircuit::new(
        [
            Node::Cmux(22, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(17, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(36, 3, 9),
            Node::Cmux(36, 3, 14),
            Node::Cmux(36, 3, 0),
            Node::Copy,
            Node::Cmux(36, 3, 1),
            Node::Cmux(36, 3, 4),
            Node::Cmux(36, 3, 6),
            Node::Cmux(36, 3, 10),
            Node::Cmux(36, 3, 8),
            Node::Cmux(36, 3, 13),
            Node::Cmux(36, 3, 5),
            Node::Cmux(36, 3, 11),
            Node::Cmux(36, 3, 2),
            Node::Cmux(36, 3, 7),
            Node::Cmux(36, 3, 12),
            Node::None,
            Node::Cmux(35, 6, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 0, 7),
            Node::None,
            Node::Cmux(35, 9, 2),
            Node::Cmux(35, 3, 1),
            Node::Cmux(35, 12, 13),
            Node::Cmux(35, 11, 8),
            Node::None,
            Node::Cmux(35, 3, 5),
            Node::None,
            Node::Cmux(35, 14, 10),
            Node::Cmux(34, 7, 1),
            Node::None,
            Node::None,
            Node::Cmux(34, 8, 14),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 10, 9),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 12, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 3, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 12, 0),
            Node::Cmux(32, 14, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        15,
    )),
    AnyBitCircuit::B18(BitCircuit::new(
        [
            Node::Cmux(25, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(18, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(36, 8, 10),
            Node::Cmux(36, 8, 12),
            Node::Cmux(36, 8, 4),
            Node::Cmux(36, 8, 11),
            Node::Cmux(36, 8, 2),
            Node::Cmux(36, 8, 6),
            Node::Cmux(36, 8, 1),
            Node::Cmux(36, 8, 0),
            Node::Copy,
            Node::Cmux(36, 8, 13),
            Node::Cmux(36, 8, 7),
            Node::Cmux(36, 8, 5),
            Node::Cmux(36, 8, 9),
            Node::Cmux(36, 8, 3),
            Node::Cmux(35, 2, 3),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(35, 8, 6),
            Node::None,
            Node::None,
            Node::Cmux(35, 8, 11),
            Node::Cmux(35, 10, 5),
            Node::Cmux(35, 1, 4),
            Node::Cmux(35, 13, 12),
            Node::Cmux(35, 0, 9),
            Node::Cmux(35, 8, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 4, 10),
            Node::None,
            Node::None,
            Node::Cmux(34, 12, 0),
            Node::None,
            Node::None,
            Node::Cmux(34, 11, 9),
            Node::Cmux(34, 7, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 4, 10),
            Node::None,
            Node::None,
            Node::Cmux(33, 7, 11),
            Node::None,
            Node::None,
            Node::Cmux(32, 11, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        14,
    )),
    AnyBitCircuit::B19(BitCircuit::new(
        [
            Node::Cmux(25, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(19, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(36, 6, 7),
            Node::Cmux(36, 6, 2),
            Node::Cmux(36, 6, 8),
            Node::Cmux(36, 6, 5),
            Node::Cmux(36, 6, 9),
            Node::Cmux(36, 6, 11),
            Node::Copy,
            Node::Cmux(36, 6, 3),
            Node::Cmux(36, 6, 10),
            Node::Cmux(36, 6, 12),
            Node::Cmux(36, 6, 0),
            Node::Cmux(36, 6, 4),
            Node::Cmux(36, 6, 1),
            Node::Cmux(35, 6, 8),
            Node::Cmux(35, 12, 1),
            Node::Cmux(35, 6, 9),
            Node::None,
            Node::None,
            Node::Cmux(35, 7, 11),
            Node::Cmux(35, 3, 5),
            Node::None,
            Node::Cmux(35, 6, 4),
            Node::None,
            Node::Cmux(35, 6, 10),
            Node::Cmux(35, 0, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 8, 6),
            Node::Cmux(34, 2, 11),
            Node::Cmux(34, 0, 1),
            Node::None,
            Node::Cmux(34, 10, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 9, 8),
            Node::None,
            Node::Cmux(33, 11, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 4, 6),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        13,
    )),
    AnyBitCircuit::B20(BitCircuit::new(
        [
            Node::Cmux(29, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(20, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(36, 11, 5),
            Node::Cmux(36, 11, 6),
            Node::Cmux(36, 11, 9),
            Node::Cmux(36, 11, 1),
            Node::Cmux(36, 11, 10),
            Node::Cmux(36, 11, 2),
            Node::Cmux(36, 11, 7),
            Node::Cmux(36, 11, 8),
            Node::Cmux(36, 11, 0),
            Node::Cmux(36, 11, 4),
            Node::Cmux(36, 11, 3),
            Node::Copy,
            Node::Cmux(35, 11, 5),
            Node::None,
            Node::Cmux(35, 8, 7),
            Node::Cmux(35, 11, 10),
            Node::Cmux(35, 11, 0),
            Node::Cmux(35, 3, 9),
            Node::Cmux(35, 11, 2),
            Node::Cmux(35, 1, 6),
            Node::None,
            Node::Cmux(35, 11, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 9, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 3, 0),
            Node::None,
            Node::Cmux(34, 6, 5),
            Node::None,
            Node::Cmux(34, 4, 7),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 10, 8),
            Node::None,
            Node::None,
            Node::Cmux(33, 6, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 7, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        12,
    )),
    AnyBitCircuit::B21(BitCircuit::new(
        [
            Node::Cmux(28, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(21, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(36, 7, 8),
            Node::Cmux(36, 7, 4),
            Node::Cmux(36, 7, 9),
            Node::Cmux(36, 7, 2),
            Node::Cmux(36, 7, 5),
            Node::Cmux(36, 7, 0),
            Node::Cmux(36, 7, 6),
            Node::Copy,
            Node::Cmux(36, 7, 3),
            Node::Cmux(36, 7, 10),
            Node::Cmux(36, 7, 1),
            Node::Cmux(35, 7, 4),
            Node::None,
            Node::None,
            Node::Cmux(35, 7, 10),
            Node::Cmux(35, 0, 2),
            Node::Cmux(35, 7, 6),
            Node::Cmux(35, 1, 8),
            Node::Cmux(35, 7, 5),
            Node::None,
            Node::Cmux(35, 7, 9),
            Node::Cmux(35, 7, 3),
            Node::None,
            Node::Cmux(34, 5, 6),
            Node::None,
            Node::None,
            Node::Cmux(34, 7, 0),
            Node::Cmux(34, 9, 3),
            Node::Cmux(34, 10, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 5, 1),
            Node::Cmux(33, 4, 6),
            Node::None,
            Node::Cmux(32, 9, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        11,
    )),
    AnyBitCircuit::B22(BitCircuit::new(
        [
            Node::Cmux(31, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(22, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Copy,
            Node::Cmux(36, 0, 9),
            Node::Cmux(36, 0, 3),
            Node::Cmux(36, 0, 8),
            Node::Cmux(36, 0, 2),
            Node::Cmux(36, 0, 7),
            Node::Cmux(36, 0, 4),
            Node::Cmux(36, 0, 5),
            Node::Cmux(36, 0, 1),
            Node::Cmux(36, 0, 6),
            Node::Cmux(35, 7, 2),
            Node::Cmux(35, 0, 6),
            Node::None,
            Node::Cmux(35, 0, 8),
            Node::Cmux(35, 0, 4),
            Node::Cmux(35, 0, 9),
            Node::Cmux(35, 0, 3),
            Node::Cmux(35, 0, 1),
            Node::Cmux(35, 0, 5),
            Node::None,
            Node::Cmux(34, 7, 6),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 8, 5),
            Node::None,
            Node::None,
            Node::Cmux(34, 4, 0),
            Node::Cmux(34, 1, 3),
            Node::None,
            Node::Cmux(33, 5, 8),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 0, 9),
            Node::None,
            Node::Cmux(32, 8, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        10,
    )),
    AnyBitCircuit::B23(BitCircuit::new(
        [
            Node::Cmux(30, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(23, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(36, 2, 5),
            Node::Cmux(36, 2, 1),
            Node::Copy,
            Node::Cmux(36, 2, 7),
            Node::Cmux(36, 2, 3),
            Node::Cmux(36, 2, 8),
            Node::Cmux(36, 2, 6),
            Node::Cmux(36, 2, 4),
            Node::Cmux(36, 2, 0),
            Node::Cmux(35, 2, 8),
            Node::Cmux(35, 2, 7),
            Node::Cmux(35, 2, 6),
            Node::Cmux(35, 2, 1),
            Node::Cmux(35, 2, 4),
            Node::Cmux(35, 2, 0),
            Node::Cmux(35, 2, 5),
            Node::Cmux(35, 2, 3),
            Node::None,
            Node::None,
            Node::Cmux(34, 4, 1),
            Node::Cmux(34, 3, 7),
            Node::Cmux(34, 5, 6),
            Node::Cmux(34, 0, 2),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 4, 3),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 2, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 0, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        9,
    )),
    AnyBitCircuit::B24(BitCircuit::new(
        [
            Node::Cmux(31, 1, 0),
            Node::Cmux(24, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Copy,
            Node::Cmux(36, 0, 3),
            Node::Cmux(36, 0, 7),
            Node::Cmux(36, 0, 4),
            Node::Cmux(36, 0, 5),
            Node::Cmux(36, 0, 6),
            Node::Cmux(36, 0, 2),
            Node::Cmux(36, 0, 1),
            Node::Copy,
            Node::Cmux(35, 0, 2),
            Node::Cmux(35, 0, 7),
            Node::Cmux(35, 0, 3),
            Node::Cmux(35, 0, 6),
            Node::Cmux(35, 0, 5),
            Node::Cmux(35, 0, 4),
            Node::Cmux(35, 0, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 1, 5),
            Node::None,
            Node::Cmux(34, 4, 7),
            Node::Cmux(34, 6, 2),
            Node::Cmux(34, 0, 3),
            Node::Cmux(33, 3, 6),
            Node::None,
            Node::None,
            Node::Cmux(33, 7, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 3, 0),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        8,
    )),
    AnyBitCircuit::B25(BitCircuit::new(
        [
            Node::Cmux(29, 1, 0),
            Node::Cmux(25, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(36, 5, 2),
            Node::Cmux(36, 5, 3),
            Node::Cmux(36, 5, 0),
            Node::Cmux(36, 5, 1),
            Node::Cmux(36, 5, 6),
            Node::Copy,
            Node::Cmux(36, 5, 4),
            Node::Cmux(35, 5, 4),
            Node::Cmux(35, 5, 3),
            Node::Cmux(35, 5, 2),
            Node::Cmux(35, 5, 6),
            Node::Cmux(35, 5, 1),
            Node::Copy,
            Node::Cmux(35, 5, 0),
            Node::Cmux(34, 5, 4),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(34, 3, 0),
            Node::Cmux(34, 5, 6),
            Node::Cmux(34, 2, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(33, 5, 4),
            Node::None,
            Node::Cmux(33, 0, 6),
            Node::None,
            Node::Cmux(32, 3, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        7,
    )),
    AnyBitCircuit::B26(BitCircuit::new(
        [
            Node::Cmux(31, 1, 0),
            Node::Cmux(27, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(26, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Copy,
            Node::Cmux(36, 0, 5),
            Node::Cmux(36, 0, 1),
            Node::Cmux(36, 0, 2),
            Node::Cmux(36, 0, 4),
            Node::Cmux(36, 0, 3),
            Node::Copy,
            Node::Cmux(35, 0, 3),
            Node::Cmux(35, 0, 2),
            Node::Cmux(35, 0, 5),
            Node::Cmux(35, 0, 4),
            Node::Cmux(35, 0, 1),
            Node::Cmux(34, 0, 5),
            Node::None,
            Node::Cmux(34, 0, 1),
            Node::Cmux(34, 0, 2),
            Node::None,
            Node::Cmux(34, 4, 3),
            Node::Cmux(33, 2, 3),
            Node::Cmux(33, 0, 5),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::Cmux(32, 0, 1),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        6,
    )),
    AnyBitCircuit::B27(BitCircuit::new(
        [
            Node::Cmux(27, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Cmux(36, 3, 4),
            Node::Cmux(36, 3, 1),
            Node::Cmux(36, 3, 0),
            Node::Copy,
            Node::Cmux(36, 3, 2),
            Node::Cmux(35, 3, 2),
            Node::Cmux(35, 3, 1),
            Node::Cmux(35, 3, 4),
            Node::Copy,
            Node::Cmux(35, 3, 0),
            Node::Cmux(34, 3, 4),
            Node::Cmux(34, 3, 0),
            Node::None,
            Node::Cmux(34, 3, 2),
            Node::Cmux(34, 3, 1),
            Node::Cmux(33, 4, 3),
            Node::None,
            Node::None,
            Node::Cmux(33, 0, 1),
            Node::None,
            Node::Cmux(32, 0, 3),
            Node::None,
            Node::None,
            Node::None,
            Node::None,
        ],
        5,
    )),
    AnyBitCircuit::B28(BitCircuit::new(
        [
            Node::Cmux(29, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(28, 1, 0),
            Node::Cmux(36, 2, 0),
            Node::Cmux(36, 2, 3),
            Node::Copy,
            Node::Cmux(36, 2, 1),
            Node::Cmux(35, 2, 1),
            Node::Cmux(35, 2, 0),
            Node::Copy,
            Node::Cmux(35, 2, 3),
            Node::Cmux(34, 2, 0),
            Node::Cmux(34, 2, 3),
            Node::Copy,
            Node::Cmux(34, 2, 1),
            Node::Cmux(33, 2, 3),
            Node::None,
            Node::None,
            Node::Cmux(33, 1, 0),
            Node::Cmux(32, 0, 3),
            Node::None,
            Node::None,
            Node::None,
        ],
        4,
    )),
    AnyBitCircuit::B29(BitCircuit::new(
        [
            Node::Cmux(31, 1, 0),
            Node::Cmux(30, 1, 0),
            Node::Cmux(29, 1, 0),
            Node::Copy,
            Node::Cmux(36, 0, 2),
            Node::Cmux(36, 0, 1),
            Node::Copy,
            Node::Cmux(35, 0, 1),
            Node::Cmux(35, 0, 2),
            Node::Copy,
            Node::Cmux(34, 0, 1),
            Node::Cmux(34, 0, 2),
            Node::Cmux(33, 0, 2),
            Node::Cmux(33, 0, 1),
            Node::None,
            Node::Cmux(32, 0, 1),
            Node::None,
            Node::None,
        ],
        3,
    )),
    AnyBitCircuit::B30(BitCircuit::new(
        [
            Node::Cmux(30, 1, 0),
            Node::Cmux(31, 1, 0),
            Node::Cmux(36, 1, 0),
            Node::Copy,
            Node::Cmux(35, 1, 0),
            Node::Copy,
            Node::Cmux(34, 1, 0),
            Node::Copy,
            Node::Cmux(33, 1, 0),
            Node::Copy,
            Node::Cmux(32, 1, 0),
            Node::None,
        ],
        2,
    )),
    AnyBitCircuit::B31(BitCircuit::new([Node::Cmux(31, 1, 0), Node::None], 2)),
]);
