cargo-features = ["edition2024"]

[package]
name = "rlwe"
version = "0.1.0"
edition = "2024"

[dependencies]
criterion = {workspace = true}
base2k = {path="../base2k"}
sampling = {path="../sampling"}
rand_distr = {workspace = true}

[[bench]]
name = "gadget_product"
harness = false